#!/usr/bin/env python3
import json, os, collections
R="research"; NOW="2026-09-03"
S=[json.loads(l) for l in open(f"{R}/SUMMARY.jsonl")]
T=[json.loads(l) for l in open(f"{R}/triage.jsonl")]
st=json.load(open(f"{R}/raw/_stats.json"))
aw=[json.loads(l) for f in ("awesome_batch1.jsonl","awesome_batch2.jsonl") for l in open(f"{R}/raw/{f}")]
probes={json.loads(l)["key"]:json.loads(l) for l in open(f"{R}/raw/probes_all.jsonl")}
# ---------- ECOSYSTEM MAP ----------
def cur(list_key, n_links, chars):
    p=probes.get(list_key.lower(),{}); last=p.get("last_commit_d")
    crit = "curada" if (n_links<300 and chars<250000) else "volcado"
    return {"url":f"https://github.com/{list_key}","tipo":"awesome/lista","items_estimados":n_links,"chars":chars,"curada_o_volcado":crit,"ultima_actualizacion_dias":(0 if last is not None and last<0 else last) if last is not None else "UNVERIFIED","criterio_inclusion_declarado":"UNVERIFIED","ha_eliminado_entradas":"UNVERIFIED","nota":"Test de curación aplicado parcialmente: tamaño + actualización; eliminación de entradas no verificada (sin API de historial)."}
meta={k["list"]:cur(k["list"],k["n_links"],k["chars"]) for k in aw if "keys" in k}
eco={"generated":NOW,"taxonomia":[
 {"cat":"Computer-use / GUI agents","frontera":"Perciben pantalla (visión o accesibilidad) y actúan con mouse/teclado sobre cualquier app.","ejemplos":["microsoft/UFO","simular-ai/Agent-S","CursorTouch/Windows-MCP","trycua/cua"]},
 {"cat":"Modelos de GUI grounding","frontera":"Pesos que mapean instrucción→coordenadas; no son agentes.","ejemplos":["UI-TARS-1.5","Holo2","POINTS-GUI-G","ZonUI-3B","GUI-Owl-1.5","Qwen3-VL"]},
 {"cat":"Parsers/percepción de pantalla","frontera":"Convierten screenshot en elementos estructurados; sin acción.","ejemplos":["microsoft/OmniParser","screenpipe (OCR continuo)","Windows OCR API","RapidOCR"]},
 {"cat":"Substrato de automatización","frontera":"Librerías sin LLM: UIA, input, captura, navegador.","ejemplos":["uiautomation","pywinauto","FlaUI","pyautogui","mss/dxcam","Playwright"]},
 {"cat":"Agentes/herramientas de navegador","frontera":"DOM/CDP o accesibilidad del navegador.","ejemplos":["playwright-mcp","browser-use","stagehand","skyvern"]},
 {"cat":"Supervisores visuales (guía, no acción)","frontera":"Observan la pantalla y guían al usuario; opcionalmente actúan acotado.","ejemplos":["Blinky","OpenGuider","screen.vision"]},
 {"cat":"Frameworks de orquestación / multi-agente","frontera":"Bucle, handoffs, estado, HITL; agnósticos del dominio.","ejemplos":["LangGraph","OpenAI Agents SDK","Pydantic AI","Claude Agent SDK","AutoGen (en declive)"]},
 {"cat":"Asistentes personales 'todo en uno'","frontera":"Producto completo con skills/marketplace; superficie de permisos máxima.","ejemplos":["OpenClaw","Hermes Agent","Dex","nanobot"]},
 {"cat":"Research agents","frontera":"Búsqueda multi-fuente + informe con citas.","ejemplos":["gpt-researcher","deer-flow","open_deep_research"]},
 {"cat":"Memoria","frontera":"Capas (vector/grafo/verbatim/markdown) vs runtimes con memoria integrada (Letta).","ejemplos":["mem0","graphiti","MemPalace","basic-memory","Letta"]},
 {"cat":"MCP: SDKs, servidores, gateways, runtimes, escáneres","frontera":"Protocolo; la seguridad vive en gateways (protocolo) o runtimes (proceso).","ejemplos":["fastmcp","modelcontextprotocol/servers","mcpgate","mcp-doorman","toolhive","mcp-scan"]},
 {"cat":"Claude Code: skills/hooks/subagentes y optimización","frontera":"Nativo (hooks con deny, subagentes con modelo/tools, skills con carga perezosa) vs colecciones de terceros (superpowers, BMAD) vs optimizadores con eval (DSPy, promptfoo).","ejemplos":["anthropics/skills","obra/superpowers","dspy","promptfoo","ccusage"]},
 {"cat":"Seguridad: sandbox SO, ACL, guardrails, benchmarks de injection","frontera":"Proceso (sandbox-runtime, AppContainer) vs fichero (Phylax) vs protocolo (gateways) vs evaluación (AgentDojo).","ejemplos":["sandbox-runtime","sandboxrs-windows","Phylax","AgentDojo","openai/codex (referencia)"]},
 {"cat":"Observabilidad y evaluación","frontera":"Trazas/coste (Langfuse, Phoenix, Opik) vs benchmarks (OSWorld, WAA, ScreenSpot-Pro, OSWorld-MCP).","ejemplos":["langfuse","OSWorld","ScreenSpot-Pro","WindowsAgentArena (muerto)"]},
 {"cat":"Modelos y runtimes locales","frontera":"Ollama/llama.cpp + pesos cuantizados; techo 2 GB VRAM.","ejemplos":["ollama","llama.cpp","Qwen3-VL-2B/4B","RapidOCR"]}],
 "fuentes_meta":meta,
 "fuentes_meta_no_github":[
  {"url":"https://gui-agent.github.io/grounding-leaderboard/","tipo":"leaderboard","nota":"ScreenSpot-Pro oficial; actualizado 2026-08-13"},
  {"url":"https://os-world.github.io/","tipo":"leaderboard","nota":"OSWorld-Verified oficial (no descargado; citado por terceros)"},
  {"url":"https://leaderboard.steel.dev/leaderboards/osworld/","tipo":"agregador","nota":"Mirror con fuentes; 2026-05-28"},
  {"url":"https://benchlm.ai/benchmarks/osworld-verified","tipo":"agregador","nota":"2026-09-02; discrepa con Steel"},
  {"url":"https://osworld-mcp.github.io/","tipo":"leaderboard","nota":"GUI + MCP; TIR/ACS"},
  {"url":"https://snorkel.ai/leaderboard/os-world-2-0/","tipo":"leaderboard","nota":"OSWorld 2.0 con coste por run"},
  {"url":"https://gentic.news/computer-use","tipo":"agregador","nota":"14 agentes / 13 benchmarks; cifras difieren de Steel/BenchLM"},
  {"url":"https://huggingface.co","tipo":"hub de modelos","nota":"cards de Qwen3-VL, UI-TARS-1.5, Holo2, OmniParser"},
  {"url":"https://code.claude.com/docs","tipo":"docs oficiales","nota":"hooks, sub-agents, skills"}]}
json.dump(eco,open(f"{R}/ecosystem-map.json","w"),ensure_ascii=False,indent=1)
# ---------- QUERIES ----------
Q=[("awesome_raw_fetch","45 listas awesome por raw.githubusercontent (batch1+2)",sum(k.get("n_links",0) for k in aw)),
 ("exa","open source Windows desktop agent using UI Automation accessibility tree with LLM",8),("exa","open-weights GUI grounding model ScreenSpot-Pro 2026 small model",8),
 ("exa","open source AI assistant that watches your screen in real time and gives step-by-step guidance",8),("exa","awesome list: agent memory, agent security, computer-use, observability 2026",8),
 ("exa","MCP gateway/proxy enforcing tool permissions, allowlists, human approval, prompt injection defense",8),("exa","tools that optimize Claude Code prompts, CLAUDE.md, skills, hooks, subagents with evaluation",8),
 ("exa","Windows Agent Arena OSWorld leaderboard 2026 best open source computer use agent",8),("exa","open source sandbox/permission layer for AI agents on Windows: AppContainer, Windows Sandbox",8),
 ("exa","critical review / security analysis of ruvnet claude-flow",5),("exa","OpenClaw security vulnerabilities CVE GHSA 2026",5),("exa","independent benchmark comparison mem0 vs zep graphiti vs letta LoCoMo LongMemEval 2026",5),
 ("exa_fetch","HF cards Qwen3-VL-2B/4B, UI-TARS-1.5-7B, Holo2-4B, ZonUI-3B(401), OmniParser-v2",6),("exa_fetch","openai.com/api/pricing + ai.google.dev pricing",2),
 ("webfetch","code.claude.com hooks / sub-agents / skills",3),("webfetch","github.com páginas de 17 finalistas (stars/issues)",17),("skill","claude-api (precios Anthropic, cache 2026-06-24)",1),
 ("raw_grep","READMEs/pyproject de UFO, Agent-S, OpenCUA, Windows-Use, OmniParser, cua, uia-agent, OpenGUI, Blinky; telemetry.py de browser-use y mem0",12)]
with open(f"{R}/queries.jsonl","w") as f:
    for src,q,n in Q: f.write(json.dumps({"source":src,"query":q,"results":n,"ts":NOW},ensure_ascii=False)+"\n")
# ---------- COVERAGE ----------
slots={"B2":["grounding_model","cu_harness","cu_cloud_agent","screen_parser","ocr_light","visual_supervisor"],"B3":["uia_driver","input","screenshot","browser_dom","desktop_app_automation","powershell_ahk"],"B4":["graph","roles","minimal_runtime","handoff","planning","checkpoints"],"B5":["deep_research","web_nav","search_layer","citation_verify"],"B6":["vector","graph","temporal_episodic","procedural","context_compression"],"B7":["official","desktop_mcp","browser_mcp","fs_terminal_mcp","gateway","client_host"],"B8":["optimizer_eval","context_claudemd","skills","hooks","routing","token_measure"],"B9":["sandbox","permissions_approval","injection_defense","mcp_security","secrets","supply_chain"],"B10":["tracing","cost","trajectories","gui_eval_suites","regression"]}
filled={"B2":{"grounding_model":"solo en models.json (UI-TARS-1.5-7B, Holo2-4B, ZonUI-3B, POINTS-GUI-G-8B, GUI-Owl-1.5): repos K9","cu_harness":"UFO, Agent-S, cua","cu_cloud_agent":"anthropic-quickstarts / openai-cua-sample-app PARKED","screen_parser":"OmniParser, screenpipe","ocr_light":"RapidOCR/PaddleOCR (models.json), Windows OCR API (Blinky)","visual_supervisor":"Blinky (+3 eliminados)"},
 "B3":{"uia_driver":"uiautomation, pywinauto, FlaUI","input":"pyautogui (muerto), pynput","screenshot":"mss, dxcam","browser_dom":"playwright-mcp, browser-use, stagehand, skyvern","desktop_app_automation":"cubierto por B2 (UFO/Windows-MCP)","powershell_ahk":"AutoHotkey PARKED; PowerShell vía Windows-MCP/Windows-Use"},
 "B4":{"graph":"LangGraph","roles":"crewAI/camel/MetaGPT PARKED","minimal_runtime":"smolagents PARKED; Claude Agent SDK","handoff":"OpenAI Agents","planning":"cubierto por Agent-S/UFO (dominio CU)","checkpoints":"LangGraph"},
 "B5":{"deep_research":"gpt-researcher, deer-flow","web_nav":"browser-use","search_layer":"firecrawl/searxng PARKED","citation_verify":"gpt-researcher (E1)"},
 "B6":{"vector":"mem0","graph":"graphiti","temporal_episodic":"graphiti, screenpipe","procedural":"basic-memory (MD) — SLOT DÉBIL: no se encontró sistema de 'workflows aprendidos' con evidencia","context_compression":"SLOT VACÍO en repos; cubierto por features nativas (Claude API compaction/context editing; Claude Code skills con carga perezosa)"},
 "B7":{"official":"modelcontextprotocol/servers, fastmcp","desktop_mcp":"Windows-MCP, heronwin PARKED","browser_mcp":"playwright-mcp","fs_terminal_mcp":"DesktopCommanderMCP (vetado), servers oficiales","gateway":"mcpgate, mcp-doorman, mcpproxy, mcpfw, toolhive","client_host":"Claude Code/Desktop (nativo); cua"},
 "B8":{"optimizer_eval":"DSPy, promptfoo","context_claudemd":"please-optimize-my-claude (K4) — SLOT DÉBIL: sin herramienta con evaluación","skills":"anthropics/skills, superpowers","hooks":"nativo (docs) + hooks-mastery (K4)","routing":"SLOT VACÍO: no se encontró router de modelos/agentes con evidencia (subagentes nativos permiten model: por agente)","token_measure":"ccusage"},
 "B9":{"sandbox":"sandbox-runtime, sandboxrs-windows, convira, landstrip","permissions_approval":"mcpgate, LangGraph interrupt, hooks nativos","injection_defense":"AgentDojo (eval); gateways (heurística)","mcp_security":"mcp-scan, gateways","secrets":"Phylax; mcp-doorman (redacción)","supply_chain":"SLOT DÉBIL: solo mcp-scan; evidencia negativa en OpenClaw/claude-flow"},
 "B10":{"tracing":"Langfuse (Phoenix/Opik PARKED)","cost":"ccusage, Langfuse","trajectories":"Langfuse (adjuntos) — no verificado para screenshots","gui_eval_suites":"OSWorld, WAA (muerto), ScreenSpot-Pro, OSWorld-MCP","regression":"promptfoo"}}
cov={"generated":NOW,"blocks":{b:{"slots":{s:filled[b].get(s,"SLOT VACÍO") for s in slots[b]}} for b in slots},"empty_or_weak":["B6.context_compression","B6.procedural","B8.context_claudemd","B8.routing","B9.supply_chain"],"budget_exhausted":[],"note":"Cupo G4 ampliado de 32 a 41 fichas para no vaciar slots; 5 bloques con slots débiles justificados arriba."}
json.dump(cov,open(f"{R}/coverage.json","w"),ensure_ascii=False,indent=1)
# ---------- MODELS ----------
M=[
 dict(nombre="Claude Fable 5.1",proveedor="Anthropic",abierto=False,modalidad="texto+imagen",contexto="1M",tool_calling=True,computer_use_nativo=True,benchmark="OSWorld-Verified 85.0% (Fable 5, sistema card, self-reported; Steel 2026-05-28)",coste_in=10.0,coste_out=50.0,cache_read=0.25,latencia="alta (turnos largos)",vram_min=None,ram_min=None,cuda=False,licencia="propietario",L="cloud",fuente="skill claude-api (cache 2026-06-24); leaderboard.steel.dev"),
 dict(nombre="Claude Opus 5",proveedor="Anthropic",abierto=False,modalidad="texto+imagen",contexto="1M",tool_calling=True,computer_use_nativo=True,benchmark="OSWorld 2.0: 31.4% binario / 68.3% parcial (Snorkel)",coste_in=5.0,coste_out=25.0,cache_read="UNVERIFIED",latencia="media-alta",vram_min=None,ram_min=None,cuda=False,licencia="propietario",L="cloud",fuente="skill claude-api; snorkel.ai"),
 dict(nombre="Claude Opus 4.8",proveedor="Anthropic",abierto=False,modalidad="texto+imagen",contexto="1M",tool_calling=True,computer_use_nativo=True,benchmark="OSWorld-Verified 83.4%; ScreenSpot-Pro 87.9% (BenchLM)",coste_in=5.0,coste_out=25.0,cache_read="UNVERIFIED",latencia="media",vram_min=None,ram_min=None,cuda=False,licencia="propietario",L="cloud",fuente="skill claude-api; benchlm.ai; steel.dev"),
 dict(nombre="Claude Sonnet 5",proveedor="Anthropic",abierto=False,modalidad="texto+imagen",contexto="1M",tool_calling=True,computer_use_nativo=True,benchmark="OSWorld-Verified 81.2%",coste_in=2.0,coste_out=10.0,cache_read="UNVERIFIED",latencia="media",vram_min=None,ram_min=None,cuda=False,licencia="propietario",L="cloud",fuente="skill claude-api; steel.dev"),
 dict(nombre="Claude Haiku 4.5",proveedor="Anthropic",abierto=False,modalidad="texto+imagen",contexto="200K",tool_calling=True,computer_use_nativo=True,benchmark="OSWorld-Verified 50.7%",coste_in=1.0,coste_out=5.0,cache_read="UNVERIFIED",latencia="baja",vram_min=None,ram_min=None,cuda=False,licencia="propietario",L="cloud",fuente="skill claude-api; steel.dev"),
 dict(nombre="GPT-5.6 Sol / Terra / Luna",proveedor="OpenAI",abierto=False,modalidad="texto+imagen",contexto="≥270K (precio estándar <270K)",tool_calling=True,computer_use_nativo="UNVERIFIED (CUA)",benchmark="OSWorld 2.0: GPT-5.6 Sol 62.6% parcial (Steel); GPT-5.4 OSWorld-V 75.0%",coste_in="5.00 / 2.00 / 0.20",coste_out="30.00 / 12.00 / 1.20",cache_read="0.50 / 0.20 / 0.02",latencia="UNVERIFIED",vram_min=None,ram_min=None,cuda=False,licencia="propietario",L="cloud",fuente="openai.com/api/pricing (Exa 2026-09-03); steel.dev"),
 dict(nombre="Gemini 3.6 Flash",proveedor="Google",abierto=False,modalidad="texto+imagen+audio",contexto="UNVERIFIED",tool_calling=True,computer_use_nativo="UNVERIFIED",benchmark="Gemini 3.5 Flash OSWorld-V (BenchLM lista sin cifra extraída)",coste_in=1.50,coste_out=7.50,cache_read=0.15,latencia="baja",vram_min=None,ram_min=None,cuda=False,licencia="propietario",L="cloud",fuente="ai.google.dev/gemini-api/docs/pricing (Exa); free tier con uso de datos para entrenar"),
 dict(nombre="Qwen3.8 Max / Qwen3.8-27B",proveedor="Alibaba",abierto="pesos abiertos (Max: UNVERIFIED)",modalidad="texto+imagen",contexto="1M",tool_calling=True,computer_use_nativo=True,benchmark="OSWorld-V 86.1% / 84.3%; ScreenSpot-Pro 84.5% (BenchLM 2026-09-02)",coste_in="UNVERIFIED",coste_out="UNVERIFIED",cache_read=None,latencia=None,vram_min=">16 GB (27B)",ram_min=">32 GB",cuda=True,licencia="UNVERIFIED",L="L4",fuente="benchlm.ai"),
 dict(nombre="Qwen3-VL-235B-A22B",proveedor="Alibaba",abierto=True,modalidad="texto+imagen",contexto="256K",tool_calling=True,computer_use_nativo=True,benchmark="OSWorld-V 66.7% (self-reported)",coste_in=None,coste_out=None,cache_read=None,latencia=None,vram_min=">100 GB",ram_min=None,cuda=True,licencia="Apache-2.0 (UNVERIFIED)",L="L4",fuente="steel.dev; HF"),
 dict(nombre="Qwen3-VL-4B-Instruct",proveedor="Alibaba",abierto=True,modalidad="texto+imagen",contexto="256K",tool_calling=True,computer_use_nativo="GUI agent declarado (card)",benchmark="UNVERIFIED para 4B",coste_in=None,coste_out=None,cache_read=None,latencia=None,vram_min="≈2.5 GB int4 (estimación mecánica 4B×0.5B+activaciones) → NO cabe cómodo en 2 GB",ram_min="≈6-8 GB CPU",cuda=False,licencia="Apache-2.0 (UNVERIFIED)",L="L1/L3",fuente="HF card"),
 dict(nombre="Qwen3-VL-2B-Instruct",proveedor="Alibaba",abierto=True,modalidad="texto+imagen",contexto="256K",tool_calling=True,computer_use_nativo="GUI agent declarado (card)",benchmark="UNVERIFIED para 2B",coste_in=None,coste_out=None,cache_read=None,latencia=None,vram_min="≈1.3 GB int4 (estimación) → candidato único a GPU 2 GB",ram_min="≈4 GB CPU",cuda=False,licencia="Apache-2.0 (UNVERIFIED)",L="L2",fuente="HF card"),
 dict(nombre="Holo2-4B",proveedor="H Company",abierto=True,modalidad="texto+imagen",contexto="UNVERIFIED",tool_calling="UNVERIFIED",computer_use_nativo=True,benchmark="ScreenSpot-Pro: Holo2-30B-A3B en top (BenchLM); 4B UNVERIFIED",coste_in=None,coste_out=None,cache_read=None,latencia=None,vram_min="≈2.5 GB int4 (4B)",ram_min="≈6-8 GB",cuda=False,licencia="Apache-2.0",L="L1/L3",fuente="HF card Hcompany/Holo2-4B (fine-tuned from Qwen3-VL-4B-Thinking)"),
 dict(nombre="UI-TARS-1.5-7B",proveedor="ByteDance",abierto=True,modalidad="texto+imagen",contexto="UNVERIFIED",tool_calling=False,computer_use_nativo=True,benchmark="OSWorld 42.5% (100 pasos); WAA 42.1%; ScreenSpot-V2 94.2% (card, self-reported)",coste_in=None,coste_out=None,cache_read=None,latencia=None,vram_min="≈4.5 GB int4 (7B)",ram_min="≈10 GB",cuda=False,licencia="Apache-2.0 (UNVERIFIED)",L="L3",fuente="HF card ByteDance-Seed/UI-TARS-1.5-7B"),
 dict(nombre="POINTS-GUI-G-8B",proveedor="WeChat/Tencent",abierto=True,modalidad="grounding",contexto=None,tool_calling=False,computer_use_nativo="grounding only",benchmark="ScreenSpot-Pro 59.9; OSWorld-G 66.0; ScreenSpot-v2 95.7 (paper)",coste_in=None,coste_out=None,cache_read=None,latencia=None,vram_min="≈5 GB int4 (8B)",ram_min="≈12 GB",cuda=False,licencia="UNVERIFIED",L="L3",fuente="arxiv.org/html/2602.06391"),
 dict(nombre="ZonUI-3B",proveedor="académico (WACV 2026)",abierto=True,modalidad="grounding",contexto=None,tool_calling=False,computer_use_nativo="grounding only",benchmark="ScreenSpot 84.9 / v2 86.4 / Pro 28.7 (paper)",coste_in=None,coste_out=None,cache_read=None,latencia=None,vram_min="≈2 GB int4 (3B) — límite",ram_min="≈6 GB",cuda=False,licencia="UNVERIFIED (repo sin LICENSE; HF 401)",L="L2/L3",fuente="arxiv 2506.23491; WACV 2026"),
 dict(nombre="SE-GUI-3B / 7B",proveedor="NKU",abierto=True,modalidad="grounding",contexto=None,tool_calling=False,computer_use_nativo="grounding only",benchmark="ScreenSpot-Pro 35.9 (3B) / 47.2 (7B)",coste_in=None,coste_out=None,cache_read=None,latencia=None,vram_min="≈2 GB int4 (3B)",ram_min=None,cuda=False,licencia="UNVERIFIED",L="L2/L3",fuente="README ScreenSpot-Pro (likaixin2000)"),
 dict(nombre="GUI-Owl-1.5-8B",proveedor="Alibaba",abierto=True,modalidad="texto+imagen",contexto=None,tool_calling="UNVERIFIED",computer_use_nativo=True,benchmark="OSWorld-V 52.9%; ScreenSpot-Pro 80.3% (gentic.news, no verificado en fuente primaria)",coste_in=None,coste_out=None,cache_read=None,latencia=None,vram_min="≈5 GB int4",ram_min=None,cuda=False,licencia="UNVERIFIED",L="L3",fuente="gentic.news/computer-use"),
 dict(nombre="OmniParser v2 (YOLOv8 + Florence-2-base)",proveedor="Microsoft",abierto=True,modalidad="detección+caption",contexto=None,tool_calling=False,computer_use_nativo="parser",benchmark="ScreenSpot-Pro 39.6; 0.8 s/frame en RTX 4090",coste_in=None,coste_out=None,cache_read=None,latencia="0.8 s/frame (4090); MX330 UNVERIFIED",vram_min="≈0.5-1 GB fp16",ram_min="≈4 GB",cuda=False,licencia="CC-BY-4.0 (repo); pesos UNVERIFIED",L="L2",fuente="HF microsoft/OmniParser-v2.0"),
 dict(nombre="Windows OCR API (WinRT)",proveedor="Microsoft (SO)",abierto=False,modalidad="OCR",contexto=None,tool_calling=False,computer_use_nativo=False,benchmark="UNVERIFIED",coste_in=0,coste_out=0,cache_read=None,latencia="baja (CPU)",vram_min="0",ram_min="0",cuda=False,licencia="parte de Windows",L="L0",fuente="Blinky README; screenpipe (OCR nativo Windows)"),
 dict(nombre="RapidOCR (ONNX)",proveedor="RapidAI",abierto=True,modalidad="OCR",contexto=None,tool_calling=False,computer_use_nativo=False,benchmark="UNVERIFIED",coste_in=0,coste_out=0,cache_read=None,latencia="baja (CPU)",vram_min="0",ram_min="<2 GB",cuda=False,licencia="Apache-2.0",L="L0",fuente="sonda repo (activo, 40 commits/90d)"),
 dict(nombre="Embeddings locales (bge-m3 / nomic-embed / MiniLM)",proveedor="varios",abierto=True,modalidad="embeddings",contexto=None,tool_calling=False,computer_use_nativo=False,benchmark="UNVERIFIED (no investigado por presupuesto)",coste_in=0,coste_out=0,cache_read=None,latencia="baja",vram_min="0",ram_min="<2 GB",cuda=False,licencia="MIT/Apache",L="L0",fuente="NO VERIFICADO EN ESTA FASE"),
 dict(nombre="Ollama / llama.cpp (runtimes)",proveedor="OSS",abierto=True,modalidad="runtime",contexto=None,tool_calling=True,computer_use_nativo=False,benchmark="n/a",coste_in=0,coste_out=0,cache_read=None,latencia="depende",vram_min="0 (CPU) / offload parcial a 2 GB",ram_min="depende del modelo",cuda="opcional (CUDA/Vulkan)",licencia="MIT",L="L0-L2",fuente="sondas: ambos activos, CI Windows"),
]
json.dump({"generated":NOW,"nota":"Clasificación L0-L4 mecánica según SCOPE-LOCK; VRAM estimada = params × 0.5 byte (int4) + margen, marcada como estimación. Precios en USD por 1M tokens. La decisión local/cloud es de OPUS.","hardware_objetivo":"i7-1065G7, 16 GB RAM, MX330 2 GB VRAM","modelos":M},open(f"{R}/models.json","w"),ensure_ascii=False,indent=1)
# ---------- PAPERS / COMMERCIAL ----------
with open(f"{R}/papers.jsonl","w") as f:
    for p in [("POINTS-GUI-G: GUI-Grounding Journey","https://arxiv.org/html/2602.06391","modelo 8B abierto; código UNVERIFIED"),("ZonUI-3B (WACV 2026)","https://arxiv.org/html/2506.23491","repo Han1018/ZonUI-3B sin LICENSE"),("BAMI: Training-Free Bias Mitigation in GUI Grounding (CVPR 2026)","https://openaccess.thecvf.com/content/CVPR2026/papers/Zhang_BAMI_Training-Free_Bias_Mitigation_in_GUI_Grounding_CVPR_2026_paper.pdf","técnica de inferencia coarse-to-fine: +5.9 pts ScreenSpot-Pro sin reentrenar; código UNVERIFIED"),("ScreenSpot-Pro","https://github.com/likaixin2000/ScreenSpot-Pro-GUI-Grounding","benchmark + leaderboard"),("Windows Agent Arena","https://arxiv.org/abs/2409.08264","benchmark Windows; repo muerto 651d; fork nice-mee usado por UFO"),("OSWorld-MCP","https://osworld-mcp.github.io/","GUI+MCP: herramientas MCP suben la precisión hasta +15.7 pts"),("Agent S3 (arXiv 2510.02250)","https://arxiv.org/abs/2510.02250","Behavior Best-of-N"),("LoCoMo (arXiv 2402.17753)","https://arxiv.org/abs/2402.17753","dataset de memoria; 10 conversaciones; sin juez canónico")]:
        f.write(json.dumps({"title":p[0],"url":p[1],"note":p[2]},ensure_ascii=False)+"\n")
with open(f"{R}/commercial.jsonl","w") as f:
    for c in [("Anthropic API (Claude)","10/50 Fable 5.1; 5/25 Opus 5; 2/10 Sonnet 5; 1/5 Haiku 4.5 USD/M","claude-api skill"),("OpenAI API","GPT-5.6 Sol 5/30, Terra 2/12, Luna 0.20/1.20; cached 10%","openai.com/api/pricing"),("Google Gemini API","3.6 Flash 1.50/7.50; free tier usa datos para entrenar","ai.google.dev"),("Mem0 Platform","grafo = Pro $249/mes (E3 blog)","dev.to"),("Zep","plataforma SaaS ~$25/mes; Graphiti abierto","rohitraj.tech"),("browser-use cloud / cua cloud / e2b","sandboxes de pago","READMEs"),("Cluely-like (Masa OSS)","asistentes de pantalla comerciales","exa")]:
        f.write(json.dumps({"name":c[0],"pricing":c[1],"source":c[2]},ensure_ascii=False)+"\n")
print("ok", len(M), "modelos")
