# -*- coding: utf-8 -*-
"""Datos autorados por FABLE para los finalistas (G4). Los campos métricos se rellenan desde probes_all.jsonl.
Escala de anclas A1..A10: 0-5 (SCORING.md). impact: -2..+3 (solo ejes != 0). Evidencias externas: (clase, url, cita<=400, claim)."""
F = {}
def add(key, **kw): F[key.lower()] = kw

# ---------------- B2 COMPUTER USE ----------------
add("microsoft/UFO", block="B2", archetype="cu_harness_windows", name="UFO² / UFO³ (Microsoft)", stars=9600,
 what="Agente de escritorio Windows de Microsoft: orquestador HostAgent + AppAgents por aplicación; percibe por árbol UIA (uiautomation/pywinauto) y visión, actúa por APIs nativas y pyautogui; incluye servidor MCP (fastmcp) y evaluación en WAA/OSWorld-Windows.",
 problem="Automatizar tareas multi-aplicación en Windows con percepción híbrida UIA+visión.",
 how="Base candidata para el COMPUTER AGENT: percepción y acción nativas en Windows; su modelo de HostAgent/AppAgent es directamente la arquitectura multi-agente que pide el documento.",
 perception="hybrid", actuation="uia_invoke", verification="Re-observa el estado tras cada acción; bundling de varios pasos validados en vivo (README: 'hasta 51% menos consultas').",
 win="W1", win_notes="Deps con marcador sys_platform=='win32': pywin32, pywinauto, uiautomation, pyautogui. Sin job windows-latest en CI (ci=1, sin tests en CI).",
 perms=["exec_shell","fs_read","fs_write","net_out","screen_capture","input_injection","credentials","env_vars"], risk="R3",
 isolation="Ninguna nativa; recomienda VM/WAA para evaluación.", approval="Hooks de confirmación configurables (approval 99 hits); UNVERIFIED que estén activos por defecto.",
 secrets="Claves en config YAML/env (msal/azure-identity opcionales).", injection="UNVERIFIED (no se encontró defensa explícita frente a contenido de pantalla).",
 models_req=["GPT-4o/OpenAI por defecto", "cualquier OpenAI-compatible", "Gemini opcional"], local_cloud="hybrid", min_vram="0 (modelo en cloud)",
 provides=["action_executor","screenshot_source","mcp_server","scheduler"], consumes=["vlm_inference","llm_client"], runtime="python3.10-3.11", transport=["stdio","http","in-process"], integration="adapter",
 scores=dict(A1=4,A2=3,A3=5,A4=2,A5=4,A6=4,A7=4,A8=4,A9=3,A10=3),
 impact=dict(computer_use=3,percepcion=3,autonomia=2,multi_agent=2,mcp=2,seguridad=-1,coste=-1),
 claims=[("Controla aplicaciones Windows vía UIA y visión","E2"),("Resultados en Windows Agent Arena y OSWorld-Windows","E1"),("Hasta 51% menos consultas LLM por bundling","E0"),("Servidor MCP integrado","E2")],
 pros=["Único harness maduro y activo (4 humanos/90d) nativo Windows con UIA+visión","Arquitectura Host/App agents = multi-agente por aplicación","Evaluación pública en WAA"], cons=["Sin CI en Windows; 137k LOC, fuerte acoplamiento a langchain 0.3","Permisos R3 sin sandbox propio","Números concretos de WAA/OSWorld solo en docs, no re-verificados"],
 contradictions=[], open=["Cifras actuales de éxito en WAA para UFO³ (README enlaza a fork nice-mee/WindowsAgentArena; no verificado el número)."],
 ext=[("E1","https://raw.githubusercontent.com/microsoft/UFO/main/requirements.txt","pywinauto==0.6.8; sys_platform == 'win32' / uiautomation==2.0.18; sys_platform == 'win32' / pyautogui==0.9.54; sys_platform == 'win32'","Dependencias nativas Windows"),
      ("E1","https://raw.githubusercontent.com/microsoft/UFO/main/ufo/README.md","Windows Agent Arena (WAA) | 154 real Windows tasks across 15 applications ... OSWorld (Windows) | 49 cross-application tasks","Evaluación en benchmarks Windows"),
      ("E3","https://github.com/microsoft/UFO","9.6k stars, 43 open issues, MIT; UFO³ Galaxy released November 2025","Popularidad y estado")],
 verdict="Harness Windows-nativo con percepción híbrida UIA+visión verificada en dependencias y código; activo; sin sandbox propio ni CI Windows; benchmarks propios en WAA/OSWorld-Windows no re-verificados.")

add("CursorTouch/Windows-MCP", block="B2", archetype="windows_mcp", name="Windows-MCP", stars=6900,
 what="Servidor MCP en Python que expone el escritorio Windows a cualquier cliente MCP: estado de UI por árbol UIA (uiautomation), captura, clic/tecleo, PowerShell, apps.",
 problem="Dar 'manos' Windows a Claude Desktop/Claude Code sin escribir un agente propio.",
 how="Capa de acción/percepción Windows conectable directamente a Claude Code o a un orquestador MCP; complementa a Windows-Use (mismo autor) y a un gateway MCP con permisos.",
 perception="accessibility_uia", actuation="input_injection", verification="Devuelve nuevo estado UIA tras la acción; sin verificación semántica (UNVERIFIED).",
 win="W1", win_notes="189 menciones Windows en README; CI windows-latest con tests; deps uiautomation/pywin32.",
 perms=["exec_shell","fs_read","fs_write","screen_capture","input_injection","clipboard"], risk="R3",
 isolation="Ninguna; README recomienda Windows Sandbox.", approval="Delegada al cliente MCP (Claude Code pide permiso por tool).", secrets="No maneja credenciales.", injection="Contenido de pantalla llega al modelo sin filtro; defensa depende del host.",
 models_req=["cualquiera (cliente MCP)"], local_cloud="local", min_vram="0",
 provides=["mcp_server","action_executor","screenshot_source"], consumes=[], runtime="python3.13", transport=["stdio"], integration="drop_in",
 scores=dict(A1=4,A2=3,A3=4,A4=2,A5=4,A6=5,A7=2,A8=3,A9=3,A10=4),
 impact=dict(computer_use=3,percepcion=2,mcp=3,claude_code=3,seguridad=-1,tokens=1),
 claims=[("Controla Windows a nivel GUI vía MCP","E2"),("Usa árbol UIA en vez de visión","E2"),("Ejecuta PowerShell","E2")],
 pros=["Drop-in para Claude Code/Desktop","Activo: 16 committers humanos/90d, tests, CI Windows","Percepción por UIA = barata en tokens"], cons=["Sin verificación de resultado","Herramienta shell sin allowlist propia","Sin benchmark"],
 contradictions=[], open=["Comportamiento con DPI/multi-monitor no verificado."],
 ext=[("E3","https://github.com/CursorTouch/Windows-MCP","6.9k stars | 836 forks | 12 open issues | MIT | Python 3.13+ MCP server for Windows UI automation","Popularidad/estado")],
 verdict="Servidor MCP Windows activo y probado en CI Windows que expone UIA + input + PowerShell; sin aprobación ni sandbox propios (delegados al host).")

add("Jeomon/Windows-Use", block="B2", archetype="windows_agent", name="Windows-Use (CursorTouch)", stars=423,
 what="Agente Python que controla Windows a nivel GUI leyendo el árbol UIA (uiautomation) y actuando con pyautogui; modelo-agnóstico; opcional visión/anotación; tools de shell, apps, escritorios virtuales.",
 problem="Agente CU Windows completo sin modelo de visión obligatorio.",
 how="Referencia de bucle observe→act sobre UIA en Windows; alternativa 'agente completo' frente a Windows-MCP (solo herramientas).",
 perception="accessibility_uia", actuation="input_injection", verification="max_consecutive_failures y re-lectura del árbol; sin verificación visual (UNVERIFIED).",
 win="W1", win_notes="Windows 10 build 17763+ / 11; CI windows-latest con tests.",
 perms=["exec_shell","fs_read","fs_write","screen_capture","input_injection","env_vars"], risk="R3",
 isolation="README recomienda Windows Sandbox.", approval="Ninguna nativa (UNVERIFIED hook de confirmación).", secrets="Parámetro secrets={} inyectado al contexto del agente (riesgo de exfiltración vía prompt).", injection="Ninguna.",
 models_req=["cualquier LLM vía LangChain"], local_cloud="hybrid", min_vram="0",
 provides=["action_executor","screenshot_source"], consumes=["llm_client"], runtime="python3.10+", transport=["in-process"], integration="adapter",
 scores=dict(A1=3,A2=3,A3=4,A4=1,A5=3,A6=5,A7=2,A8=3,A9=2,A10=4),
 impact=dict(computer_use=2,percepcion=2,autonomia=2,seguridad=-2),
 claims=[("Controla Windows sin modelo de visión","E2"),("Soporta Windows 10/11","E1"),("Memoria persistente entre pasos","E0")],
 pros=["Bucle CU Windows completo en 32k LOC","CI Windows"], cons=["bus factor 0.87, 57 días sin commit","shell_tool sin control","secrets en contexto del modelo"],
 contradictions=[], open=["Tasa de éxito real: sin benchmark."],
 ext=[("E3","https://github.com/Jeomon/Windows-Use","Stars 423, Forks 55, Open Issues 2, MIT","Estado")],
 verdict="Agente Windows UIA funcional y probado en CI; seguridad débil (shell libre, secrets en prompt); mantenimiento de un solo autor.")

add("SuperMarioYL/uia-agent", block="B2", archetype="windows_agent_uia", name="uia-agent", stars=1,
 what="Agente mínimo (~4k LOC) que usa el árbol UIA de Windows como action space: observe (UIA podado ≤400 nodos) → think (Anthropic tool-use u OpenAI JSON) → act (patrones UIA Invoke/Value/SelectionItem) → verify (re-snapshot). Fallback OCR opcional; adaptadores LangChain; servidor MCP.",
 problem="Controlar software Windows legado por UIA con coste de tokens bajo (3-6k por paso) y sin selectores humanos.",
 how="Patrón de referencia para un COMPUTER AGENT determinista y barato; su poda del árbol UIA es reutilizable.",
 perception="accessibility_uia", actuation="uia_invoke", verification="Re-snapshot del árbol tras cada acción (paso 'verify' en el bucle).",
 win="W1", win_notes="Solo Windows por diseño; sesión interactiva; CI windows-latest con tests (12 tests).",
 perms=["input_injection","screen_capture","net_out","env_vars"], risk="R2",
 isolation="Ninguna.", approval="Ninguna (presupuesto de 25 pasos).", secrets="API keys por env.", injection="Ninguna.",
 models_req=["Anthropic o OpenAI API"], local_cloud="cloud", min_vram="0",
 provides=["action_executor","mcp_server"], consumes=["llm_client"], runtime="python3.12+", transport=["stdio","in-process"], integration="adapter",
 scores=dict(A1=3,A2=3,A3=4,A4=3,A5=3,A6=4,A7=1,A8=3,A9=0,A10=4),
 impact=dict(computer_use=2,percepcion=2,precision=1,tokens=2,coste=2),
 claims=[("Bucle observe→think→act→verify sobre UIA","E2"),("Hit-rate 83% en BENCHMARK.md","E0"),("~50x menos tokens que agentes de píxeles","E0")],
 pros=["Diseño limpio y verificable, sin shell ni filesystem","Verificación explícita","Activo hoy (30 commits/90d)"], cons=["1 estrella, 3 committers: riesgo de abandono","Benchmark declarado como 'valor objetivo', no medido","No hace nada fuera de UIA salvo OCR fallback"],
 contradictions=[], open=["BENCHMARK.md declara que el 83% es un target no medido: confirmar si ya hay medición real."],
 ext=[("E1","https://github.com/SuperMarioYL/uia-agent","把 UIA 无障碍树当成 LLM agent 的 action space ... 每步成本 UIA 遍历 + ~3-6k token ... BENCHMARK.md 活的成绩单 ... v0.2.0 先给出参考目标值，待首次真机 Windows 跑测后替换为实测值","Diseño y estado del benchmark (auto-declarado como no medido)")],
 verdict="HIDDEN_GEM candidato: agente UIA Windows pequeño, con verificación y MCP, activo; sin comunidad ni benchmark medido; superficie de permisos baja (R2).")

add("microsoft/OmniParser", block="B2", archetype="screen_parser", name="OmniParser v2", stars=25400,
 what="Parser de pantalla: YOLOv8 afinado (detección de iconos interactivos) + Florence-2-base (captions) que convierte screenshots en elementos estructurados para cualquier LLM; incluye OmniTool para controlar una VM Windows 11.",
 problem="Grounding visual para modelos sin capacidad nativa de localizar elementos.",
 how="Capa de percepción local (modelos pequeños) para el VISION AGENT cuando UIA no expone controles (apps Electron/juegos/Roblox Studio).",
 perception="vision_vlm", actuation="none", verification="none",
 win="W4", win_notes="OmniTool controla una VM Windows 11 (Docker/VM); el parser en sí corre nativo (PyTorch) en cualquier SO. Latencia publicada 0.8 s/frame en RTX 4090; en MX330 2GB: UNVERIFIED.",
 perms=["screen_capture","net_out"], risk="R2",
 isolation="N/A (librería)", approval="N/A", secrets="N/A", injection="N/A",
 models_req=["YOLOv8 (~6M params)","Florence-2-base (0.23B)"], local_cloud="local", min_vram="UNVERIFIED (Florence-2-base fp16 ≈0.5 GB pesos; latencia en MX330 desconocida)",
 provides=["vlm_inference"], consumes=["screenshot_source"], runtime="python", transport=["in-process"], integration="adapter",
 scores=dict(A1=4,A2=2,A3=3,A4=3,A5=1,A6=2,A7=4,A8=3,A9=4,A10=3),
 impact=dict(percepcion=3,computer_use=2,precision=1,coste=1),
 claims=[("39.5-39.6% en ScreenSpot-Pro","E3"),("Mejor rendimiento en Windows Agent Arena (2024)","E1"),("0.6 s/frame en A100, 0.8 s en 4090","E1")],
 pros=["Único parser local pequeño con número público en ScreenSpot-Pro","Modelo-agnóstico"], cons=["Licencia CC-BY-4.0 para código (atípica); pesos con licencias propias (YOLO AGPL upstream: UNVERIFIED)","44 días sin commits, 2 humanos/90d, 173 issues abiertas, sin tests","Superado en grounding por VLMs modernos (Qwen3-VL/Holo2)"],
 contradictions=["HF card dice 39.6 ScreenSpot-Pro; README dice 39.5."], open=["Licencia efectiva de los pesos YOLOv8 afinados (Ultralytics es AGPL-3.0)."],
 ext=[("E3","https://huggingface.co/microsoft/OmniParser-v2.0","60% improvement in latency compared to V1. Avg latency: 0.6s/frame on A100, 0.8s on single 4090. Strong performance: 39.6 average accuracy on ScreenSpot Pro","Latencia y benchmark"),
      ("E3","https://github.com/microsoft/OmniParser","25.4k stars | 173 open issues | License: CC-BY-4.0 | Latest Release V2 (2025/2)","Estado y licencia")],
 verdict="Parser de pantalla local con benchmark público pero mantenimiento débil y licencia atípica; útil como fallback de percepción cuando no hay UIA.")

add("simular-ai/Agent-S", block="B2", archetype="cu_harness", name="Agent S3 (gui-agents)", stars=12200,
 what="Framework agente CU (Linux/Mac/Windows) con planificación, memoria narrativa/episódica, grounding por modelo externo y 'Behavior Best-of-N'; SOTA declarado en OSWorld (72.6%) y WAA (56.6%).",
 problem="Harness CU de investigación con resultados publicados y reproducibles en OSWorld.",
 how="Referencia de arquitectura (planner + grounding + memoria de experiencia) y fuente de técnicas; menos apto como base Windows que UFO.",
 perception="vision_vlm", actuation="input_injection", verification="Reflexión por LLM entre pasos; Best-of-N con juez.",
 win="W2", win_notes="README: soporta Windows; usa pyautogui; requiere tesseract; sin CI Windows; solo 1 test.",
 perms=["exec_shell","fs_write","screen_capture","input_injection","net_out","env_vars"], risk="R3",
 isolation="Ninguna (pensado para VMs de benchmark).", approval="Ninguna.", secrets="Env.", injection="Ninguna.",
 models_req=["GPT-5/Claude para razonamiento","UI-TARS-1.5-7B u otro grounding"], local_cloud="cloud", min_vram="0 (grounding en cloud) / 7B si local",
 provides=["action_executor"], consumes=["vlm_inference","llm_client"], runtime="python3.12", transport=["in-process"], integration="fork_required",
 scores=dict(A1=4,A2=2,A3=4,A4=1,A5=2,A6=3,A7=5,A8=3,A9=3,A10=1),
 impact=dict(computer_use=2,autonomia=2,precision=2,coste=-2,seguridad=-2),
 claims=[("72.6% OSWorld (100 pasos, Best-of-N)","E3"),("56.6% Windows Agent Arena","E1"),("Soporta Windows","E1")],
 pros=["Mejor evidencia pública de rendimiento entre harnesses abiertos","Técnicas transferibles (memoria de experiencia, Best-of-N)"], cons=["Actividad baja (2 commits/90d, 1 humano)","Best-of-N multiplica coste x3","Sin seguridad ni tests"],
 contradictions=["Leaderboard Steel.dev lista 'Agent S2 + Claude 3.7' en 34.5% (50 pasos) mientras README de S3 declara 72.6% (100 pasos, BoN): no comparables por configuración."],
 open=["Reproducción independiente del 72.6%."],
 ext=[("E1","https://raw.githubusercontent.com/simular-ai/Agent-S/main/README.md","Agent S3 alone reaches 66% in the 100-step setting ... With the addition of Behavior Best-of-N, performance climbs even higher to 72.6% ... On WindowsAgentArena, accuracy rises from 50.2% ... to 56.6%","Resultados auto-reportados"),
      ("E3","https://leaderboard.steel.dev/leaderboards/osworld/","| 17 | Agent S2 + Claude 3.7 | 34.5% | Simular AI | Open-source modular agent; evaluated on 50-step OSWorld tasks.","Resultado de terceros (versión anterior)")],
 verdict="Harness de investigación con los mejores números públicos entre abiertos, pero poco activo, caro y sin seguridad; valor como referencia técnica más que como componente.")

add("trycua/cua", block="B2", archetype="cu_harness_sandbox", name="Cua (c/ua)", stars=None,
 what="Plataforma CU: drivers de escritorio en segundo plano para macOS/Windows/Linux, sandboxes (contenedor/VM), agente multi-modelo, MCP server, y benchmarks (OSWorld, ScreenSpot, WAA).",
 problem="Ejecutar agentes CU en entornos aislados y en background sin robar el foco.",
 how="Su driver Windows 'background' y el servidor MCP podrían dar acción sin bloquear al usuario; su sandbox exige VM/Docker.",
 perception="hybrid", actuation="input_injection", verification="UNVERIFIED",
 win="W2", win_notes="Driver Windows nativo (win32: 35 hits, UIA: 19) + CI windows-latest; el sandbox completo requiere Docker/VM (W4/W5). 12 hits de curl|bash en docs.",
 perms=["exec_shell","fs_write","screen_capture","input_injection","net_out","credentials","telemetry"], risk="R3",
 isolation="Sandboxes propios (contenedor/VM) para el agente; el driver host corre sin aislar.", approval="Configurable (UNVERIFIED por defecto).", secrets="Env/.env", injection="UNVERIFIED",
 models_req=["multi-proveedor"], local_cloud="hybrid", min_vram="0",
 provides=["action_executor","sandbox","mcp_server","eval_harness"], consumes=["vlm_inference"], runtime="python3.11+", transport=["stdio","http"], integration="adapter",
 scores=dict(A1=4,A2=3,A3=4,A4=2,A5=4,A6=3,A7=3,A8=4,A9=3,A10=2),
 impact=dict(computer_use=2,seguridad=1,observabilidad=1,coste=-1),
 claims=[("Drivers de escritorio en background en Windows","E2"),("Evalúa en OSWorld/ScreenSpot/WAA","E1"),("Sandboxes Windows","E1")],
 pros=["Activo (60 commits/90d), 455 tests, CI Windows","Une driver + sandbox + evaluación"], cons=["703k LOC: complejidad alta","Telemetría (249 hits) y curl|bash en docs","Producto comercial con nube propia (lock-in potencial)"],
 contradictions=[], open=["Stars no verificadas; comportamiento del driver Windows 'background' con apps DirectX."],
 ext=[("E1","https://raw.githubusercontent.com/trycua/cua/main/README.md","Cua Drivers - Background computer-use on macOS, Windows, and Linux ... Evaluate computer-use agents on OSWorld, ScreenSpot, Windows Arena","Capacidades declaradas")],
 verdict="Plataforma CU amplia y activa con driver Windows real; complejidad y telemetría altas; el aislamiento fuerte exige VM/Docker.")

add("KingSahil/Blinky", block="B2", archetype="visual_supervisor_windows", name="Blinky", stars=12,
 what="Tutor de escritorio Windows offline-first (Tauri 2 + Python): captura con dxcam, OCR con Windows OCR API (WinRT) + UIA (pywinauto), LLM local (Ollama gemma4:e4b) o cloud, overlay transparente que resalta dónde clicar; modo autopilot acotado (≤5 intentos).",
 problem="Exactamente el 'AI supervisor visual' del §4 del documento: observa la pantalla y guía paso a paso, en Windows y en local.",
 how="Prueba de concepto más cercana al caso de uso 'guíame en Roblox Studio/VS Code'; su overlay y su preflight classifier (evita capturar pantalla si no hace falta) son patrones reutilizables.",
 perception="hybrid", actuation="input_injection", verification="Bucle autopilot re-lee la pantalla; SetWindowDisplayAffinity excluye su overlay de la captura.",
 win="W1", win_notes="Windows-first (WinRT OCR, dxcam, pywinauto); Docker solo para SearXNG opcional.",
 perms=["exec_shell","screen_capture","input_injection","net_out","fs_write"], risk="R3",
 isolation="Ninguna.", approval="Autopilot limitado a 'safe clicks' y 5 intentos (E1).", secrets="API keys opcionales.", injection="Ninguna.",
 models_req=["Ollama gemma4:e4b local","Groq llama-4-scout opcional"], local_cloud="hybrid", min_vram="gemma4:e4b ≈ 4B efectivos → L3 en GPU o L1 en CPU (UNVERIFIED en MX330)",
 provides=["screenshot_source","action_executor"], consumes=["llm_client","vlm_inference"], runtime="python3.11 + bun + rust", transport=["in-process"], integration="fork_required",
 scores=dict(A1=3,A2=2,A3=4,A4=2,A5=2,A6=4,A7=1,A8=3,A9=0,A10=4),
 impact=dict(computer_use=2,percepcion=2,investigacion=1,coste=2,autonomia=1),
 claims=[("Guía visual con overlay en Windows","E2"),("OCR con Windows OCR API","E1"),("Funciona offline con Ollama","E1")],
 pros=["Único proyecto encontrado que implementa el 'supervisor visual' en Windows nativo y local","Activo (59 commits/90d), 41 tests"], cons=["12 estrellas, bus factor 0.83, sin CI, sin fichero LICENSE (badge MIT sin fichero)","Proyecto de hackathon: 3 lenguajes/runtimes","Sin evaluación de precisión"],
 contradictions=["README muestra badge MIT pero el clon no contiene fichero LICENSE (license_file=None)."], open=["Latencia real del bucle en hardware i7-1065G7/MX330."],
 ext=[("E1","https://raw.githubusercontent.com/KingSahil/Blinky/main/README.md","OCR | Windows OCR API (WinRT), Falls back to pytesseract | Screen Capture | dxcam | Window Detection | pywinauto | AI Runtime | Ollama (Local) | AI Model | gemma4:e4b","Stack Windows local"),
      ("E3","https://github.com/KingSahil/Blinky","12 stars, 4 forks, 6 open issues, MIT license ... 212 commits","Estado")],
 verdict="Prototipo activo que demuestra el supervisor visual Windows-local; inmaduro (sin licencia efectiva, sin CI, un autor). Valioso como referencia de diseño, no como dependencia.")

add("mediar-ai/screenpipe", block="B2", archetype="screen_recorder_ocr", name="screenpipe", stars=None,
 what="Grabación continua 24/7 de pantalla y audio en local (Rust), con OCR (Windows OCR nativo en Windows) y transcripción, indexado en SQLite y expuesto por API/MCP para agentes; 'memoria visual' del PC.",
 problem="Memoria episódica de lo que el usuario vio/hizo, consultable por el agente.",
 how="Fuente de contexto para el MEMORY AGENT y para 'detectar si estoy haciendo bien una tarea' con historial; alto riesgo de privacidad.",
 perception="ocr", actuation="none", verification="none",
 win="W1", win_notes="Rust nativo, CI windows-latest, UIA/win32 hits; instalador Windows.",
 perms=["screen_capture","fs_write","net_out","telemetry","autostart"], risk="R2",
 isolation="Datos en SQLite local.", approval="N/A", secrets="N/A", injection="Texto OCR de cualquier ventana llega al agente: superficie de prompt injection indirecta.",
 models_req=["OCR nativo; Whisper local opcional"], local_cloud="local", min_vram="0 (CPU) ; Whisper opcional",
 provides=["memory_store","screenshot_source","mcp_server"], consumes=[], runtime="rust + node", transport=["http","stdio"], integration="adapter",
 scores=dict(A1=4,A2=3,A3=2,A4=2,A5=4,A6=4,A7=1,A8=3,A9=3,A10=3),
 impact=dict(memoria=3,percepcion=2,contexto=2,seguridad=-2,observabilidad=1),
 claims=[("Graba pantalla 24/7 en local","E2"),("OCR nativo Windows","E2"),("Expone MCP","E2")],
 pros=["Nativo Windows, activo (60 commits/90d), 747 tests","Memoria episódica visual sin cloud"], cons=["Telemetría (384 hits) y licencia 'OTHER' (verificar términos)","1M LOC","Graba todo: credenciales en pantalla acaban en SQLite"],
 contradictions=[], open=["Términos exactos de la licencia; telemetría por defecto."],
 ext=[], verdict="Grabador de pantalla local y activo con OCR nativo Windows y MCP; riesgo de privacidad estructural (captura todo) y licencia/telemetría a verificar.")

# ---------------- B3 SUBSTRATO ----------------
add("microsoft/playwright-mcp", block="B3", archetype="browser_mcp", name="Playwright MCP", stars=36800,
 what="Servidor MCP oficial de Playwright: expone el navegador vía árbol de accesibilidad (snapshot estructurado) en lugar de píxeles; acciones por referencia de elemento.",
 problem="Automatización de navegador determinista y barata en tokens para clientes MCP.",
 how="Capa de navegador del agente (research + tareas web) conectada a Claude Code; complementaria a Windows-MCP (escritorio).",
 perception="dom", actuation="cdp_dom", verification="Devuelve snapshot posterior; sin juez semántico.",
 win="W1", win_notes="Node; CI windows-latest con tests; Docker opcional.",
 perms=["browser_profile","net_out","fs_write"], risk="R3",
 isolation="Perfil de navegador aislado por defecto (UNVERIFIED si persistente por defecto).", approval="Delegada al host MCP.", secrets="Cookies del perfil.", injection="Contenido web llega al modelo sin filtro.",
 models_req=["cualquiera"], local_cloud="local", min_vram="0",
 provides=["mcp_server","browser_driver"], consumes=[], runtime="node", transport=["stdio","http"], integration="drop_in",
 scores=dict(A1=4,A2=4,A3=3,A4=3,A5=5,A6=5,A7=2,A8=4,A9=5,A10=5),
 impact=dict(investigacion=2,computer_use=1,mcp=3,claude_code=2,tokens=2,coste=1),
 claims=[("Automatiza navegador por accesibilidad, no por screenshots","E2"),("Oficial Microsoft","E3")],
 pros=["Oficial, activo, 1 issue abierta, CI Windows","Barato en tokens (texto, no imágenes)"], cons=["Sin benchmark propio","Sin política de permisos interna"],
 contradictions=[], open=[], ext=[("E3","https://github.com/microsoft/playwright-mcp","Stars: 36.8k | Open Issues: 1 | Apache-2.0","Estado")],
 verdict="Capa de navegador MCP oficial, madura y Windows-nativa; la seguridad depende del host.")

add("browser-use/browser-use", block="B3", archetype="browser_agent", name="browser-use", stars=112200,
 what="Agente de navegador Python (Playwright/CDP) con extracción DOM + visión opcional, MCP, sandbox cloud propio; telemetría anónima activada por defecto (opt-out por env).",
 problem="Agente web autónomo completo, modelo-agnóstico.",
 how="RESEARCH/BROWSER AGENT ya montado; alternativa 'agente' frente a playwright-mcp 'herramienta'.",
 perception="hybrid", actuation="cdp_dom", verification="Juez LLM de finalización de tarea (UNVERIFIED en detalle).",
 win="W1", win_notes="CI windows-latest con tests.",
 perms=["browser_profile","net_out","fs_write","exec_shell","telemetry","env_vars"], risk="R3",
 isolation="Sandbox cloud opcional (de pago).", approval="Hooks/eventos; sin gate por defecto.", secrets="sensitive_data con enmascarado (E1).", injection="Ninguna explícita.",
 models_req=["multi-proveedor"], local_cloud="hybrid", min_vram="0",
 provides=["browser_driver","mcp_server","action_executor"], consumes=["llm_client"], runtime="python3.11+", transport=["stdio","in-process"], integration="adapter",
 scores=dict(A1=5,A2=3,A3=3,A4=2,A5=5,A6=4,A7=3,A8=4,A9=5,A10=3),
 impact=dict(investigacion=3,autonomia=2,mcp=1,seguridad=-1,tokens=-1),
 claims=[("WebVoyager 89%","E3"),("Telemetría anónima desactivable","E2")],
 pros=["Comunidad enorme; 6 humanos/90d; 123 tests","Modelo-agnóstico"], cons=["Telemetría PostHog activa por defecto (V5 parcial: eventos, no screenshots)","5 hits curl|bash en docs de skills","Empuja hacia su cloud"],
 contradictions=[], open=["Qué campos exactos envía la telemetría."],
 ext=[("E2","https://raw.githubusercontent.com/browser-use/browser-use/main/browser_use/telemetry/service.py","If the environment variable `ANONYMIZED_TELEMETRY=False`, anonymized telemetry will be disabled. ... POSTHOG_HOST = 'https://eu.i.posthog.com'","Telemetría opt-out"),
      ("E3","https://gentic.news/computer-use","the agent frameworks OpenHands, Browser Use (WebVoyager 89%), Magentic-One and Playwright MCP","Benchmark de terceros")],
 verdict="Agente de navegador maduro y activo; telemetría por defecto y sin gate de aprobación nativo.")

add("yinkaisheng/Python-UIAutomation-for-Windows", block="B3", archetype="uia_driver", name="uiautomation (Python-UIAutomation-for-Windows)", stars=None,
 what="Binding Python del API UI Automation de Windows (COM); base de UFO, Windows-Use, Windows-MCP y uia-agent.",
 problem="Leer/invocar controles Windows por accesibilidad.",
 how="Dependencia transversal del substrato Windows; su salud condiciona a los cuatro agentes anteriores.",
 perception="accessibility_uia", actuation="uia_invoke", verification="none",
 win="W1", win_notes="Solo Windows.", perms=["input_injection","screen_capture"], risk="R2",
 isolation="N/A", approval="N/A", secrets="N/A", injection="N/A", models_req=[], local_cloud="local", min_vram="0",
 provides=["action_executor"], consumes=[], runtime="python", transport=["in-process"], integration="drop_in",
 scores=dict(A1=4,A2=2,A3=3,A4=4,A5=2,A6=5,A7=2,A8=3,A9=4,A10=5),
 impact=dict(percepcion=2,computer_use=2,tokens=1),
 claims=[("Binding completo de UIA","E2")], pros=["Estándar de facto (4 finalistas dependen de él)"], cons=["1 autor (bus 1.0), 92 días sin commit, 5 tests, sin CI"],
 contradictions=[], open=[], ext=[], verdict="Dependencia crítica del stack Windows-UIA mantenida por una sola persona; riesgo de abandono a vigilar.")

# ---------------- B4 ORQUESTACIÓN ----------------
add("langchain-ai/langgraph", block="B4", archetype="graph", name="LangGraph", stars=None,
 what="Orquestación de agentes como grafo de estado con checkpoints persistentes, interrupciones human-in-the-loop, reintentos y time-travel.",
 problem="Coordinar agentes con estado durable y puntos de aprobación.",
 how="Núcleo de orquestación del MAIN AGENT (checkpoints + interrupt() para acciones sensibles).",
 perception="none", actuation="none", verification="none", win="W1", win_notes="Python puro.",
 perms=["fs_write","net_out"], risk="R1", isolation="N/A", approval="interrupt()/Command nativos (E2 approval 72 hits)", secrets="N/A", injection="N/A",
 models_req=["cualquiera"], local_cloud="hybrid", min_vram="0",
 provides=["scheduler","approval_gate"], consumes=["llm_client","memory_store"], runtime="python", transport=["in-process"], integration="adapter",
 scores=dict(A1=5,A2=4,A3=2,A4=4,A5=5,A6=4,A7=3,A8=5,A9=5,A10=4),
 impact=dict(multi_agent=3,autonomia=2,seguridad=2,observabilidad=1,contexto=1),
 claims=[("Checkpoints e interrupciones HITL","E2")], pros=["11 humanos/90d, 220 tests","HITL y persistencia de primera clase"], cons=["Ecosistema LangChain pesado","Curva de aprendizaje"],
 contradictions=[], open=[], ext=[], verdict="Orquestador de grafo maduro con HITL y checkpoints verificados en código.")

add("openai/openai-agents-python", block="B4", archetype="handoff", name="OpenAI Agents SDK", stars=None,
 what="SDK ligero: agentes, handoffs, guardrails de entrada/salida, tracing integrado, MCP; proveedor-agnóstico vía LiteLLM.",
 problem="Multi-agente con handoffs y guardrails con poca ceremonia.",
 how="Alternativa a LangGraph con menos complejidad; guardrails = SECURITY AGENT básico.",
 perception="none", actuation="none", verification="none", win="W1", win_notes="CI windows-latest con tests.",
 perms=["net_out"], risk="R1", isolation="N/A", approval="Aprobación de tools MCP (approval 350 hits)", secrets="N/A", injection="Guardrails por LLM/regla.",
 models_req=["OpenAI por defecto; otros vía LiteLLM"], local_cloud="hybrid", min_vram="0",
 provides=["scheduler","approval_gate","trace_sink"], consumes=["llm_client"], runtime="python", transport=["in-process"], integration="adapter",
 scores=dict(A1=4,A2=4,A3=2,A4=4,A5=5,A6=5,A7=3,A8=5,A9=5,A10=4),
 impact=dict(multi_agent=3,seguridad=2,observabilidad=2,mcp=2),
 claims=[("Handoffs y guardrails","E2"),("Soporte MCP con aprobación","E2")], pros=["20 humanos/90d, 381 tests, CI Windows","Simple"], cons=["Sesgo a OpenAI; tracing por defecto a OpenAI (verificar opt-out)"],
 contradictions=[], open=["Destino por defecto del tracing."], ext=[], verdict="SDK multi-agente activo, simple, con guardrails y aprobación MCP verificados; sesgo a OpenAI.")

add("pydantic/pydantic-ai", block="B4", archetype="typed", name="Pydantic AI", stars=None,
 what="Framework de agentes tipado (salidas validadas), multi-proveedor, con MCP, human-in-the-loop, evals y observabilidad (Logfire/OTel).",
 problem="Agentes fiables por tipado estricto y evaluación integrada.",
 how="Base alternativa del orquestador con validación de salidas y OTel nativo.",
 perception="none", actuation="none", verification="none", win="W1", win_notes="Python puro.",
 perms=["net_out"], risk="R1", isolation="N/A", approval="Deferred tools / approval (E2 approval 346 hits)", secrets="N/A", injection="Validación por tipos (parcial).",
 models_req=["Anthropic/OpenAI/Gemini/Ollama..."], local_cloud="hybrid", min_vram="0",
 provides=["scheduler","approval_gate","trace_sink","eval_harness"], consumes=["llm_client"], runtime="python", transport=["in-process"], integration="adapter",
 scores=dict(A1=4,A2=5,A3=2,A4=4,A5=5,A6=4,A7=3,A8=5,A9=4,A10=4),
 impact=dict(multi_agent=2,precision=2,observabilidad=2,mcp=2,calidad=2),
 claims=[("Salidas tipadas y validadas","E2"),("OTel integrado","E2")], pros=["12 humanos/90d, 326 tests","Multi-proveedor real"], cons=["Sin Windows CI (no crítico: Python puro)"],
 contradictions=[], open=[], ext=[], verdict="Framework tipado, activo y multi-proveedor con HITL, evals y OTel verificados por sondas.")

add("anthropics/claude-agent-sdk-python", block="B4", archetype="runtime", name="Claude Agent SDK (Python)", stars=None,
 what="Claude Code empaquetado como librería: bucle, tools integradas (Read/Write/Bash/Grep/Web), hooks, subagentes, permisos, MCP y sesiones.",
 problem="Reutilizar el harness de Claude Code (permisos, hooks, MCP) como núcleo del agente personal.",
 how="Candidato a MAIN AGENT si el usuario quiere que su agente sea 'Claude Code con manos': permisos por tool, hooks PreToolUse para aprobación, MCP para Windows-MCP/playwright-mcp.",
 perception="none", actuation="shell", verification="none", win="W1", win_notes="CI windows-latest con tests; requiere Claude Code CLI (Node).",
 perms=["exec_shell","fs_read","fs_write","net_out","credentials"], risk="R3", isolation="Sandbox opcional (sandbox-runtime, Windows alpha).", approval="Sistema de permisos + hooks PreToolUse con deny (E3 docs).", secrets="ANTHROPIC_API_KEY / OAuth.", injection="Sin filtro de contenido; hooks permiten añadirlo.",
 models_req=["Claude (Anthropic API o suscripción)"], local_cloud="cloud", min_vram="0",
 provides=["scheduler","approval_gate","skill_registry"], consumes=["mcp_server","llm_client"], runtime="python + node", transport=["in-process","stdio"], integration="drop_in",
 scores=dict(A1=4,A2=4,A3=2,A4=4,A5=4,A6=5,A7=2,A8=4,A9=3,A10=2),
 impact=dict(claude_code=3,mcp=3,seguridad=2,multi_agent=2,prompting=2,coste=-1),
 claims=[("Hooks pueden bloquear tools en Windows","E3"),("Subagentes con modelo y tools propios","E3")], pros=["Permisos y hooks ya construidos y documentados","CI Windows"], cons=["Lock-in a Claude; bus factor 0.82","Coste: modelos Anthropic únicamente"],
 contradictions=[], open=[],
 ext=[("E3","https://code.claude.com/docs/en/hooks","PreToolUse | Before tool execution | Yes | Exit 2 or JSON permissionDecision: deny ... All hook events run on Windows via PowerShell or cmd.exe","Hooks con bloqueo en Windows"),
      ("E3","https://code.claude.com/docs/en/sub-agents","model: sonnet, opus, haiku, full ID, or inherit | tools allowlist | permissionMode | mcpServers | hooks | memory","Subagentes configurables")],
 verdict="Harness con permisos/hooks/MCP/subagentes documentados y CI Windows; dependiente de Claude.")

add("NousResearch/hermes-agent", block="B4", archetype="personal_assistant", name="Hermes Agent", stars=None,
 what="Asistente personal autónomo open source (Nous): tools, memoria, skills, multi-canal; 1.3M LOC; 4.895 tests; instalador curl|bash.",
 problem="Asistente personal 'todo en uno' autohospedado.",
 how="Referencia de asistente completo; superficie de permisos muy amplia.",
 perception="none", actuation="shell", verification="none", win="W2", win_notes="CI windows-latest; 15 menciones Windows; 35 hits curl|bash (instalador).",
 perms=["exec_shell","fs_write","net_out","credentials","env_vars","telemetry"], risk="R4", isolation="Sandbox opcional (704 hits) UNVERIFIED por defecto.", approval="UNVERIFIED", secrets="Env", injection="UNVERIFIED",
 models_req=["multi-proveedor"], local_cloud="hybrid", min_vram="0",
 provides=["scheduler","memory_store","skill_registry"], consumes=["llm_client","mcp_server"], runtime="python", transport=["in-process"], integration="fork_required",
 scores=dict(A1=4,A2=3,A3=2,A4=1,A5=4,A6=3,A7=1,A8=3,A9=3,A10=3),
 impact=dict(autonomia=2,memoria=1,multi_agent=1,seguridad=-2),
 claims=[("Asistente autónomo con memoria y skills","E2")], pros=["Muy activo (20 humanos/90d)"], cons=["Instalación por curl|bash (V1 si es la única vía: UNVERIFIED)","R4 sin evidencia de aprobación por defecto","1.3M LOC"],
 contradictions=[], open=["¿Existe vía de instalación sin script remoto?","¿Aprobación de acciones por defecto?"], ext=[], verdict="Asistente completo y muy activo pero con superficie de permisos máxima y sin evidencia de gates por defecto.")

add("openclaw/openclaw", block="B4", archetype="personal_assistant", name="OpenClaw", stars=None,
 what="Plataforma de asistente personal autónomo (Node) con marketplace de skills/plugins (ClawHub), gateway MCP loopback, sandbox OpenShell. Aparece en 5 listas curadas.",
 problem="Asistente personal extensible por skills.",
 how="Base de Dex (Windows-first) y de muchos forks; pero historial de seguridad grave documentado (véase evidencias).",
 perception="none", actuation="shell", verification="none", win="W2", win_notes="CI windows-latest; postinstall script en package.json; 6 instaladores.",
 perms=["exec_shell","fs_write","net_out","credentials","env_vars","telemetry","net_listen"], risk="R4", isolation="OpenShell (vulnerado por CVE-2026-44112/44113 TOCTOU).", approval="Allowlist de comandos (evadida por CVE-2026-44115).", secrets="Env; exfiltradas en varios CVEs.", injection="UNVERIFIED",
 models_req=["multi-proveedor"], local_cloud="hybrid", min_vram="0",
 provides=["scheduler","skill_registry","memory_store"], consumes=["llm_client","mcp_server"], runtime="node", transport=["http","ws"], integration="fork_required",
 scores=dict(A1=4,A2=3,A3=2,A4=0,A5=5,A6=3,A7=2,A8=3,A9=4,A10=3),
 impact=dict(autonomia=2,seguridad=-2,mcp=1),
 claims=[("Sandbox OpenShell aísla al agente","E3-REFUTES"),("Marketplace de skills seguro","E3-REFUTES")],
 pros=["Muy activo (12 humanos/90d, 13k tests)","Ecosistema grande"], cons=["Cadena de 4 CVEs (mayo 2026) que rompe el sandbox, CVSS 9.6","Campaña de 341 skills maliciosas (12% de 2.857 auditadas) en ClawHub","RCE en instalación de plugins (GHSA-m3mh-3mpg-37hw) y bypass de metadata (CVE-2026-53810)"],
 contradictions=[], open=["Estado de parches en la versión actual."],
 ext=[("E3","https://labs.cloudsecurityalliance.org/research/csa-research-note-openclaw-claw-chain-sandbox-escape-2026051/","Four vulnerabilities in OpenClaw's sandbox and MCP loopback runtime — CVE-2026-44112, CVE-2026-44113, CVE-2026-44115, and CVE-2026-44118 — can be chained ... CVE-2026-44112 carries a CVSS score of 9.6 (Critical)","Escape del sandbox"),
      ("E3","https://github.com/openclaw/openclaw/issues/16052","This skill is part of a confirmed 341-skill supply chain attack against the OpenClaw ecosystem (12% infection rate of 2,857 audited skills) ... Malware Families: Atomic Stealer (macOS), ClickFix (Windows)","Supply chain en marketplace"),
      ("E3","https://github.com/openclaw/openclaw/security/advisories/GHSA-m3mh-3mpg-37hw","During the installation phase of OpenClaw local plugins/hooks, the Git executable can be hijacked by a project-level .npmrc file, leading to arbitrary code execution during installation.","RCE en instalación"),
      ("E3","https://aithreatalert.com/cve/CVE-2026-53810","OpenClaw before 2026.5.18 allows an attacker with trusted operator access to manipulate marketplace extension metadata, redirecting plugin loading to unscanned package payloads ... CVSS 8.8","Bypass de escaneo")],
 verdict="Proyecto muy activo y popular con historial de seguridad 2026 grave y repetido (sandbox roto, marketplace infectado, RCE en instalación). Capado por V6/V3.")

# ---------------- B5 RESEARCH ----------------
add("assafelovic/gpt-researcher", block="B5", archetype="deep_research", name="GPT Researcher", stars=None,
 what="Agente de investigación profunda: planificador + sub-agentes de búsqueda, scraping, citas, informes; MCP; multi-proveedor; Docker opcional.",
 problem="Investigación web autónoma con fuentes citadas.",
 how="RESEARCH AGENT listo, integrable por MCP o librería.",
 perception="none", actuation="none", verification="Verificación cruzada de fuentes por LLM (E1).", win="W1", win_notes="Python; Docker solo opcional (12 menciones).",
 perms=["net_out","fs_write","env_vars","telemetry"], risk="R1", isolation="N/A", approval="N/A", secrets="Env", injection="Contenido web al modelo sin filtro.",
 models_req=["multi-proveedor"], local_cloud="hybrid", min_vram="0",
 provides=["mcp_server"], consumes=["llm_client","browser_driver"], runtime="python", transport=["stdio","in-process"], integration="drop_in",
 scores=dict(A1=4,A2=3,A3=1,A4=3,A5=4,A6=4,A7=2,A8=4,A9=4,A10=3),
 impact=dict(investigacion=3,autonomia=1,coste=-1),
 claims=[("Genera informes con citas","E2"),("Aparece en 6 listas curadas","E3")], pros=["Activo (6 humanos/90d), 128 tests","6 listas curadas"], cons=["Sin benchmark tipo BrowseComp","Telemetría (11 hits) a verificar"],
 contradictions=[], open=["Telemetría por defecto."], ext=[], verdict="Agente de research maduro, activo y modelo-agnóstico; sin evidencia de benchmark.")

add("bytedance/deer-flow", block="B5", archetype="deep_research", name="DeerFlow", stars=None,
 what="Framework de deep research (LangGraph) de ByteDance con búsqueda, crawling, ejecución de código, MCP; 40 humanos/90d; despliegue centrado en Docker (64 menciones).",
 problem="Deep research con orquestación explícita y ejecución de código.",
 how="Alternativa a GPT Researcher basada en LangGraph (encaja si el orquestador es LangGraph).",
 perception="none", actuation="shell", verification="UNVERIFIED", win="W3", win_notes="Guías Docker/WSL; sin CI Windows.",
 perms=["exec_code","net_out","fs_write","env_vars"], risk="R3", isolation="Docker recomendado.", approval="UNVERIFIED", secrets="Env", injection="Ninguna.",
 models_req=["multi-proveedor"], local_cloud="hybrid", min_vram="0",
 provides=["scheduler"], consumes=["llm_client","browser_driver","mcp_server"], runtime="python + node", transport=["http"], integration="fork_required",
 scores=dict(A1=4,A2=3,A3=1,A4=2,A5=5,A6=2,A7=1,A8=3,A9=3,A10=3),
 impact=dict(investigacion=3,multi_agent=1,seguridad=-1),
 claims=[("Deep research con ejecución de código","E2")], pros=["Muy activo (40 humanos, bus 0.10)"], cons=["Docker-céntrico (W3)","Ejecución de código sin sandbox nativo"],
 contradictions=[], open=[], ext=[], verdict="Deep research muy activo pero orientado a Docker; ejecución de código sin aislamiento nativo.")

# ---------------- B6 MEMORIA ----------------
add("mem0ai/mem0", block="B6", archetype="vector_memory", name="Mem0", stars=64700,
 what="Capa de memoria (extracción automática de hechos, vectorial + grafo) para agentes; SDK open source; grafo completo y plataforma gestionada de pago; telemetría PostHog activada por defecto.",
 problem="Memoria de usuario/preferencias con poco esfuerzo de integración.",
 how="Memoria semántica 'bolt-on' del agente; benchmarks propios discutidos.",
 perception="none", actuation="none", verification="none", win="W1", win_notes="Python; vector store local (Qdrant/Chroma) posible.",
 perms=["net_out","fs_write","telemetry","env_vars"], risk="R1", isolation="N/A", approval="N/A", secrets="API keys del LLM", injection="Memorias envenenables (sin control de identidad).",
 models_req=["LLM para extracción + embeddings"], local_cloud="hybrid", min_vram="0 (Ollama opcional)",
 provides=["memory_store"], consumes=["llm_client"], runtime="python/ts", transport=["in-process","http"], integration="drop_in",
 scores=dict(A1=4,A2=3,A3=2,A4=2,A5=5,A6=4,A7=2,A8=4,A9=5,A10=3),
 impact=dict(memoria=3,contexto=1,tokens=1,seguridad=-1),
 claims=[("SOTA en LoCoMo (~91-92%)","E3-REFUTES"),("Telemetría desactivable","E2")],
 pros=["Comunidad mayor, activo (14 humanos)","Integración trivial"], cons=["Benchmarks auto-reportados no reproducidos (58-66% independientes; 32.4% OSS en LongMemEval)","Grafo completo tras plan de pago","Telemetría por defecto"],
 contradictions=["Vendor: 91.6-92.5% LoCoMo; independientes: 58-66%; OSS en LongMemEval 32-49% vs 93.4% plataforma."],
 open=["Configuración exacta de los reruns independientes."],
 ext=[("E2","https://raw.githubusercontent.com/mem0ai/mem0/main/mem0/memory/telemetry.py","MEM0_TELEMETRY = os.environ.get(\"MEM0_TELEMETRY\", \"True\") ... HOST = \"https://us.i.posthog.com\"","Telemetría por defecto"),
      ("E3","https://dreaming.press/posts/ai-agent-memory-benchmarks-locomo-mem0-zep.html","Mem0 reports 66.9% accuracy at 0.71s median latency and ~1,800 tokens per conversation, while independent reruns land closer to 58–66%","Benchmarks contestados"),
      ("E3","https://dev.to/everest_an/-i-benchmarked-ai-agent-memory-in-2026-and-the-numbers-tell-a-different-story-than-the-marketing-2ae4","an independent test of Mem0's open-source edition scored 32.4% on LongMemEval while the vendor's managed platform self-reports 93.4%","OSS vs plataforma"),
      ("E3","https://dreaming.press/posts/how-to-read-an-agent-memory-benchmark.html","a long-context model beats the best memory system by 35.2 points on LoCoMo and 33.4 on LongMemEval ... Mem0 reports ~7K tokens and 1.44s p95 versus 25K+ tokens and 17.12s for full-context","Memoria = coste, no precisión")],
 verdict="Memoria más adoptada; sus cifras de precisión no se reproducen; el valor real es coste/latencia; features clave de pago; telemetría por defecto.")

add("getzep/graphiti", block="B6", archetype="graph_memory", name="Graphiti (Zep)", stars=30600,
 what="Motor de grafo de conocimiento temporal (hechos con validez en el tiempo) para agentes; open source; la plataforma Zep completa es SaaS.",
 problem="Memoria que modela cambios de estado ('antes X, ahora Y').",
 how="Memoria de conocimiento del usuario/proyecto cuando importa 'qué cambió cuándo'; requiere Neo4j/FalkorDB.",
 perception="none", actuation="none", verification="none", win="W2", win_notes="Requiere base de grafos (Neo4j Desktop en Windows o Docker).",
 perms=["net_out","fs_write","telemetry"], risk="R1", isolation="N/A", approval="N/A", secrets="LLM keys", injection="Hechos envenenables.",
 models_req=["LLM + embeddings"], local_cloud="hybrid", min_vram="0",
 provides=["memory_store","mcp_server"], consumes=["llm_client"], runtime="python", transport=["in-process","stdio"], integration="adapter",
 scores=dict(A1=4,A2=4,A3=1,A4=3,A5=5,A6=3,A7=2,A8=4,A9=4,A10=2),
 impact=dict(memoria=3,contexto=1,coste=-1),
 claims=[("Grafo temporal","E2"),("~84% LoCoMo","E3-REFUTES")],
 pros=["15 humanos/90d, bus 0.22","Mejor en preguntas temporales/relacionales (E3)"], cons=["Zep corrigió su propio LoCoMo de ~84% a 58.44%","Coste en tokens/latencia ~2-3x vs Mem0 (E3)","Necesita servidor de grafos"],
 contradictions=["Zep 84% → 58.44% tras corrección; Mem0 replicó 58.44%; Zep rebate 75.14%."], open=[],
 ext=[("E3","https://hamzashabbir.dev/article/agent-memory-mem0-vs-letta-vs-zep-vs-langmem-benchmark-2026","Zep | Temporal knowledge graph | 91% | ~310 ms | ~620 tokens ... Mem0 | 84% | ~120 ms | ~280","Comparativa independiente en bot de soporte")],
 verdict="Motor de grafo temporal activo y verificado; precisión superior solo en preguntas temporales; benchmarks propios corregidos a la baja.")

add("mempalace/mempalace", block="B6", archetype="local_verbatim_memory", name="MemPalace", stars=58800,
 what="Memoria local-first en Python: almacena conversaciones verbatim y recupera por búsqueda semántica sin llamadas a API; MCP nativo; benchmark propio 96.6% R@5 LongMemEval.",
 problem="Memoria sin cloud ni coste por token.",
 how="Memoria episódica/semántica 100% local para el agente personal (privacidad).",
 perception="none", actuation="none", verification="none", win="W1", win_notes="CI windows-latest con tests; Docker opcional.",
 perms=["fs_write","telemetry"], risk="R1", isolation="Local.", approval="N/A", secrets="N/A", injection="Memoria envenenable.",
 models_req=["embeddings locales"], local_cloud="local", min_vram="0",
 provides=["memory_store","mcp_server"], consumes=[], runtime="python", transport=["stdio","in-process"], integration="drop_in",
 scores=dict(A1=4,A2=3,A3=1,A4=4,A5=4,A6=5,A7=2,A8=3,A9=4,A10=5),
 impact=dict(memoria=3,coste=2,seguridad=1,tokens=1),
 claims=[("96.6% R@5 LongMemEval sin API","E1"),("Local-first, MIT","E2")],
 pros=["Local, sin coste por token, MIT, CI Windows","Crecimiento muy rápido (58.8k stars, v3.9.0)"], cons=["Benchmark auto-reportado (R@5 de recuperación, no QA end-to-end)","360 issues abiertas: crecimiento supera al mantenimiento","Telemetría (27 hits) a verificar"],
 contradictions=["Blogs citan 54.1k y 58.8k stars y v3.4.0/v3.9.0: crecimiento muy rápido en semanas."], open=["¿Telemetría por defecto?","Verificación independiente del 96.6%."],
 ext=[("E3","https://rohitraj.tech/en/notes/open-source-ai-agent-memory-mem0-vs-zep-letta-2026","MemPalace hit ~54.1k GitHub stars and shipped v3.4.0 on June 6, 2026, scoring 96.6% R@5 on LongMemEval with zero API calls (fully local, MIT)","Estado y benchmark"),
      ("E3","https://github.com/mempalace/mempalace","58.8k stars | 360 open issues | MIT | v3.9.0","Estado")],
 verdict="Memoria local activa y popular con benchmark propio de recuperación; sin verificación independiente; backlog de issues alto.")

add("basicmachines-co/basic-memory", block="B6", archetype="local_md_memory_mcp", name="Basic Memory", stars=None,
 what="Memoria persistente en ficheros Markdown locales + grafo de conocimiento, expuesta por MCP a Claude Desktop/Code; AGPL.",
 problem="Memoria legible por humanos, local y editable.",
 how="Memoria procedural/notas del agente (workflows aprendidos) que el usuario puede leer y corregir.",
 perception="none", actuation="none", verification="none", win="W1", win_notes="CI windows-latest con tests.",
 perms=["fs_write","telemetry"], risk="R1", isolation="Local.", approval="N/A", secrets="N/A", injection="Ficheros MD envenenables.",
 models_req=[], local_cloud="local", min_vram="0",
 provides=["memory_store","mcp_server"], consumes=[], runtime="python", transport=["stdio"], integration="drop_in",
 scores=dict(A1=3,A2=3,A3=1,A4=4,A5=3,A6=5,A7=1,A8=4,A9=3,A10=5),
 impact=dict(memoria=2,claude_code=2,contexto=1,coste=1),
 claims=[("Memoria en Markdown local vía MCP","E2")], pros=["Transparente y auditable","CI Windows, 601 tests"], cons=["1 humano/90d (bus 1.0)","AGPL"],
 contradictions=[], open=[], ext=[], verdict="Memoria local en Markdown vía MCP, probada en Windows; un solo mantenedor.")

# ---------------- B7 MCP ----------------
add("modelcontextprotocol/servers", block="B7", archetype="official_mcp", name="MCP reference servers", stars=None,
 what="Servidores de referencia oficiales (filesystem, git, memory, fetch, time...).", problem="Herramientas MCP básicas auditables.",
 how="Filesystem/fetch/memory base; el resto del ecosistema (miles de servidores comunitarios) requiere gateway.", perception="none", actuation="none", verification="none",
 win="W1", win_notes="Node/Python.", perms=["fs_read","fs_write","net_out"], risk="R2", isolation="N/A", approval="Host.", secrets="N/A", injection="N/A",
 models_req=[], local_cloud="local", min_vram="0", provides=["mcp_server"], consumes=[], runtime="node/python", transport=["stdio"], integration="drop_in",
 scores=dict(A1=3,A2=4,A3=1,A4=4,A5=5,A6=5,A7=2,A8=4,A9=5,A10=5), impact=dict(mcp=2,claude_code=1),
 claims=[("Oficiales","E3")], pros=["31 humanos/90d"], cons=["Funcionalidad básica"], contradictions=[], open=[], ext=[], verdict="Referencia oficial, activa, básica.")

add("jlowin/fastmcp", block="B7", archetype="mcp_sdk", name="FastMCP", stars=None,
 what="Framework Python para construir servidores/clientes MCP con auth, proxy y composición; usado por UFO y muchos servidores.",
 problem="Escribir servidores MCP propios (p. ej. envolver UIA o Blinky) rápido.", how="SDK para construir los MCP propios del agente.",
 perception="none", actuation="none", verification="none", win="W1", win_notes="CI windows-latest.", perms=["net_out"], risk="R1", isolation="N/A", approval="N/A", secrets="N/A", injection="N/A",
 models_req=[], local_cloud="local", min_vram="0", provides=["mcp_server"], consumes=[], runtime="python", transport=["stdio","http"], integration="drop_in",
 scores=dict(A1=5,A2=4,A3=1,A4=3,A5=5,A6=5,A7=2,A8=5,A9=5,A10=5), impact=dict(mcp=3,claude_code=1),
 claims=[("SDK MCP completo","E2")], pros=["13 humanos/90d, 419 tests, CI Windows"], cons=[], contradictions=[], open=[], ext=[], verdict="SDK MCP maduro y activo.")

add("stacklok/toolhive", block="B7", archetype="mcp_runtime", name="ToolHive", stars=None,
 what="Runtime que ejecuta servidores MCP en contenedores con permisos declarativos, registro y gestión de secretos (Go).",
 problem="Aislar servidores MCP de terceros a nivel de proceso/contenedor.", how="Capa de aislamiento de MCPs no confiables; en Windows implica Docker (W4).",
 perception="none", actuation="none", verification="none", win="W4", win_notes="Contenedores → Docker Desktop en Windows; no aísla MCPs que necesitan el escritorio (Windows-MCP).",
 perms=["exec_code","net_out","credentials"], risk="R2", isolation="Contenedores + perfiles de permisos.", approval="Políticas.", secrets="Gestor de secretos integrado.", injection="N/A",
 models_req=[], local_cloud="local", min_vram="0", provides=["sandbox","mcp_server"], consumes=["mcp_server"], runtime="go", transport=["stdio","http"], integration="adapter",
 scores=dict(A1=4,A2=4,A3=1,A4=5,A6=2,A5=5,A7=2,A8=4,A9=3,A10=4), impact=dict(seguridad=3,mcp=2,coste=-1),
 claims=[("Aísla MCPs en contenedores con permisos","E2")], pros=["22 humanos/90d, 1.095 tests"], cons=["Docker en Windows; inútil para MCPs de escritorio"], contradictions=[], open=[], ext=[], verdict="Aislamiento de MCPs maduro pero basado en contenedores (W4).")

add("maksym-mishchenko/mcpgate", block="B7", archetype="mcp_gateway", name="mcpgate", stars=None,
 what="Gateway MCP zero-trust en Go: política YAML deny-by-default por tool/recurso/prompt/sampling, aprobación humana en dashboard local, auditoría SQLite write-ahead con cadena HMAC, scanner de injection/tool-poisoning.",
 problem="Poner allow/deny/ask y auditoría delante de cualquier servidor MCP.",
 how="SECURITY AGENT/HUMAN APPROVAL mecánico entre el orquestador y Windows-MCP/playwright-mcp/filesystem.",
 perception="none", actuation="none", verification="none", win="W1", win_notes="Binario Go; sin CI Windows (no crítico).",
 perms=["net_listen","fs_write"], risk="R1", isolation="Solo protocolo (no proceso).", approval="ask → UI local, timeout=deny (E1).", secrets="N/A", injection="Scanner determinista opt-in a bloqueo.",
 models_req=[], local_cloud="local", min_vram="0", provides=["approval_gate","trace_sink"], consumes=["mcp_server"], runtime="go", transport=["stdio","http"], integration="drop_in",
 scores=dict(A1=4,A2=3,A3=1,A4=5,A5=3,A6=4,A7=1,A8=4,A9=0,A10=5), impact=dict(seguridad=3,observabilidad=2,mcp=2),
 claims=[("Deny-by-default con aprobación humana","E1"),("Fail-closed en auditoría","E1")], pros=["Diseño fail-closed explícito","Activo hoy (22 commits/90d), 22 tests"], cons=["1 autor","Un servidor por proceso","Sin verificación externa"],
 contradictions=[], open=["Stars y adopción (no verificadas)."],
 ext=[("E1","https://github.com/maksym-mishchenko/mcpgate","Write-ahead SQLite audit: calls are logged before forwarding, and audit failure denies the call ... `ask` parks the call for human approval and auto-denies on timeout","Fail-closed y aprobación")],
 verdict="HIDDEN_GEM candidato: gateway MCP deny-by-default con aprobación y auditoría; un solo autor.")

add("invariantlabs-ai/mcp-scan", block="B7", archetype="mcp_scanner", name="mcp-scan", stars=None,
 what="Escáner de configuraciones y servidores MCP: detecta tool poisoning, rug pulls, cross-origin escalation; modo proxy opcional.",
 problem="Auditar servidores MCP antes/durante su uso.", how="Chequeo previo de cada MCP comunitario que se añada.",
 perception="none", actuation="none", verification="none", win="W1", win_notes="CI windows-latest.", perms=["fs_read","net_out"], risk="R1", isolation="N/A", approval="N/A", secrets="N/A", injection="Detección.",
 models_req=[], local_cloud="hybrid", min_vram="0", provides=["eval_harness"], consumes=["mcp_server"], runtime="python", transport=["in-process"], integration="drop_in",
 scores=dict(A1=3,A2=3,A3=1,A4=4,A5=4,A6=5,A7=2,A8=3,A9=3,A10=4), impact=dict(seguridad=2,mcp=1),
 claims=[("Detecta tool poisoning","E2")], pros=["Activo (9 humanos)"], cons=["Análisis puede enviar descripciones de tools a la nube de Invariant (verificar)"], contradictions=[], open=["Modo local puro."], ext=[], verdict="Escáner MCP activo; verificar exfiltración de metadatos a su servicio.")

add("wonderwhy-er/DesktopCommanderMCP", block="B7", archetype="terminal_fs_mcp", name="Desktop Commander MCP", stars=None,
 what="Servidor MCP popular de terminal + filesystem + edición para Claude Desktop; postinstall script; telemetría.",
 problem="Dar shell y ficheros a Claude Desktop.", how="Alternativa a las tools nativas de Claude Code; superficie R4.",
 perception="none", actuation="shell", verification="none", win="W1", win_notes="Node; 13 menciones Windows.", perms=["exec_shell","fs_write","fs_delete","net_out","telemetry"], risk="R4", isolation="Ninguna.", approval="Host.", secrets="N/A", injection="N/A",
 models_req=[], local_cloud="local", min_vram="0", provides=["mcp_server","action_executor"], consumes=[], runtime="node", transport=["stdio"], integration="drop_in",
 scores=dict(A1=4,A2=3,A3=2,A4=1,A5=4,A6=4,A7=1,A8=3,A9=4,A10=4), impact=dict(claude_code=1,autonomia=1,seguridad=-2),
 claims=[("Shell y FS completos vía MCP","E2")], pros=["Activo"], cons=["postinstall script + telemetría (29 hits) + shell sin límites","Redundante con tools nativas de Claude Code"], contradictions=[], open=["Qué hace el postinstall."], ext=[], verdict="MCP de shell/FS popular con postinstall y telemetría; redundante y R4.")

# ---------------- B8 CLAUDE CODE / PROMPTING ----------------
add("stanfordnlp/dspy", block="B8", archetype="prompt_optimizer_eval", name="DSPy", stars=None,
 what="Framework de programación declarativa de LLMs con optimizadores (MIPROv2, GEPA) que mejoran prompts contra métricas medidas.",
 problem="Optimización de prompts con evaluación, no 'embellecimiento'.", how="Optimizar las instrucciones de subagentes/skills contra evals propios (categoría 'prompt optimizer + evaluator').",
 perception="none", actuation="none", verification="Métrica de eval.", win="W1", win_notes="Python.", perms=["net_out","fs_write"], risk="R1", isolation="N/A", approval="N/A", secrets="N/A", injection="N/A",
 models_req=["cualquiera"], local_cloud="hybrid", min_vram="0", provides=["eval_harness"], consumes=["llm_client"], runtime="python", transport=["in-process"], integration="adapter",
 scores=dict(A1=5,A2=4,A3=0,A4=4,A5=5,A6=4,A7=4,A8=4,A9=5,A10=3), impact=dict(prompting=3,precision=2,calidad=2,coste=-1),
 claims=[("Optimizadores con métricas","E2")], pros=["18 humanos/90d, papers"], cons=["Requiere dataset/eval; coste de optimización"], contradictions=[], open=[], ext=[], verdict="Único optimizador de prompts con evaluación rigurosa entre los candidatos.")

add("promptfoo/promptfoo", block="B8", archetype="prompt_eval", name="promptfoo", stars=None,
 what="Evaluación y red-teaming de prompts/agentes/MCP con asserts, regresión y CI; Node.",
 problem="Evaluar y detectar regresiones de prompts/agentes.", how="Capa de evaluación/regresión del agente (antes/después) y red-team de sus MCP.",
 perception="none", actuation="none", verification="Asserts.", win="W1", win_notes="CI windows-latest.", perms=["net_out","fs_write","telemetry"], risk="R1", isolation="N/A", approval="N/A", secrets="N/A", injection="Red-team.",
 models_req=["cualquiera"], local_cloud="hybrid", min_vram="0", provides=["eval_harness"], consumes=["llm_client","mcp_server"], runtime="node", transport=["in-process"], integration="drop_in",
 scores=dict(A1=5,A2=4,A3=0,A4=4,A5=5,A6=5,A7=3,A8=5,A9=5,A10=4), impact=dict(prompting=2,seguridad=2,observabilidad=2,calidad=2),
 claims=[("Evals con regresión y red-team","E2")], pros=["1.237 tests, activo"], cons=["Telemetría (206 hits) a verificar"], contradictions=[], open=["Telemetría por defecto."], ext=[], verdict="Evaluador de prompts/agentes maduro con red-team; telemetría a verificar.")

add("obra/superpowers", block="B8", archetype="skills_system", name="Superpowers", stars=None,
 what="Colección de skills/workflows para Claude Code (brainstorm→plan→TDD→review) en formato SKILL.md; aparece en 5 listas.",
 problem="Procedimientos reutilizables y disciplina de trabajo para Claude Code.", how="Ejemplo de 'agent fluency' por skills; se instala como plugin.",
 perception="none", actuation="none", verification="none", win="W1", win_notes="Markdown/scripts.", perms=["exec_shell"], risk="R2", isolation="N/A", approval="Host.", secrets="N/A", injection="Skills = instrucciones: revisarlas.",
 models_req=[], local_cloud="local", min_vram="0", provides=["skill_registry"], consumes=[], runtime="markdown", transport=["in-process"], integration="drop_in",
 scores=dict(A1=3,A2=2,A3=0,A4=3,A5=4,A6=5,A7=0,A8=4,A9=4,A10=5), impact=dict(claude_code=2,prompting=2,calidad=1),
 claims=[("Mejora resultados de Claude Code","E0")], pros=["7 humanos/90d, 5 listas"], cons=["Sin evaluación/benchmark de impacto (E0)"], contradictions=[], open=[], ext=[], verdict="Skills populares sin evidencia medida de mejora.")

add("ryoppippi/ccusage", block="B8", archetype="token_measure", name="ccusage", stars=None,
 what="CLI que analiza los logs locales de Claude Code y reporta tokens/coste por sesión, día y modelo.",
 problem="Medir consumo de tokens/coste de Claude Code.", how="Instrumentación básica de coste del agente (observabilidad de tokens).",
 perception="none", actuation="none", verification="none", win="W1", win_notes="Node; CI windows-latest.", perms=["fs_read"], risk="R0", isolation="N/A", approval="N/A", secrets="N/A", injection="N/A",
 models_req=[], local_cloud="local", min_vram="0", provides=["trace_sink"], consumes=[], runtime="node", transport=["in-process"], integration="drop_in",
 scores=dict(A1=3,A2=3,A3=0,A4=5,A5=4,A6=5,A7=2,A8=4,A9=4,A10=5), impact=dict(tokens=2,coste=2,observabilidad=1),
 claims=[("Coste por sesión desde logs locales","E2")], pros=["Local, R0"], cons=["bus factor 1.0; 4 tests"], contradictions=[], open=[], ext=[], verdict="Medidor local de tokens de Claude Code; sencillo y seguro; un autor.")

add("ruvnet/claude-flow", block="B8", archetype="hype_check", name="claude-flow / ruflo", stars=27000,
 what="'Plataforma de orquestación' para Claude Code (254 tools MCP, 'neural', 'swarm'); 806k LOC; auditorías independientes (2026) documentan features simuladas, benchmarks fabricados, --dangerously-skip-permissions hardcodeado y un preinstall ofuscado retirado.",
 problem="(declarado) orquestación multi-agente y ahorro de tokens.", how="Caso de estudio de hype; NO como componente.",
 perception="none", actuation="shell", verification="none", win="W2", win_notes="CI windows-latest.", perms=["exec_shell","fs_write","net_out","net_listen","telemetry","env_vars"], risk="R4", isolation="Ninguna.", approval="Desactivada por diseño en subprocesos (E3).", secrets="N/A", injection="Sin auth en MCP (E3).",
 models_req=["Claude"], local_cloud="cloud", min_vram="0", provides=["scheduler"], consumes=["llm_client"], runtime="node", transport=["stdio","ws"], integration="fork_required",
 scores=dict(A1=2,A2=1,A3=0,A4=0,A5=4,A6=3,A7=0,A8=2,A9=3,A10=1), impact=dict(claude_code=-1,seguridad=-2,tokens=-1),
 claims=[("84.8% SWE-bench","E3-REFUTES"),("30-50% ahorro de tokens","E3-REFUTES"),("Orquesta agentes reales","E3-PARTIAL")],
 pros=["Mantenedor responde y corrige tras auditorías"], cons=["216 bugs catalogados; 'prototipo disfrazado de release' (auditoría independiente)","simulate_benchmarks.py con random.uniform (retirado tras auditoría)","--dangerously-skip-permissions en 5 sitios; MCP sin autenticación (AgentSeal)","Preinstall ofuscado en v3.5.3 (issue #1261)"],
 contradictions=["Auditoría AlphaSignal (v3.6.30) vs respuesta del mantenedor (v3.7.0-alpha): 5 de 6 gaps 'remediados'; tool descriptions siguen abiertas."],
 open=["Estado real de las remediaciones en la versión estable."],
 ext=[("E3","https://github.com/ruvnet/ruflo/issues/1425","the most damaging pattern is not any single defect but a systemic practice of returning fabricated success responses from unimplemented features ... The codebase is best characterized as a prototype masquerading as a stable release","Auditoría independiente"),
      ("E3","https://github.com/ruvnet/ruflo/issues/1896","`simulate_benchmarks.py` generates results with `random.uniform(-0.05, 0.05)`. Ruflo does not appear on the official SWE-bench leaderboard. Claims of '84.8% on SWE-bench' are synthesized, not verified.","Benchmarks fabricados"),
      ("E3","https://agentseal.org/mcp/https-githubcom-ruvnet-claude-flow/exploit-report","--dangerously-skip-permissions hardcoded in 5 locations. Every automated Claude subprocess runs without safety guardrails ... 254 tools ... No tool requires authentication","Seguridad"),
      ("E3","https://github.com/ruvnet/ruflo/issues/1482","Version v3.5.3 removed an obfuscated preinstall script that was classified as a supply-chain security risk (issue #1261)","Supply chain")],
 verdict="HYPE_FLAG + SECURITY_VETO: popularidad alta con features simuladas y prácticas inseguras documentadas por terceros; el mantenedor corrige, pero la confianza está comprometida.")

# ---------------- B9 SEGURIDAD ----------------
add("anthropic-experimental/sandbox-runtime", block="B9", archetype="os_sandbox", name="sandbox-runtime (srt)", stars=5100,
 what="Sandbox de proceso a nivel SO (Seatbelt/bubblewrap; Windows alpha con cuenta local dedicada + filtro WFP de egress + ACLs NTFS) con proxy de red allow-only; usado por Claude Code.",
 problem="Restringir filesystem y red de comandos/MCPs sin contenedor.",
 how="Aislamiento de las tools de shell/MCP del agente en Windows (alpha).",
 perception="none", actuation="none", verification="none", win="W2", win_notes="Windows alpha: requiere instalación elevada (crea usuario srt-sandbox y filtros WFP); CI windows-latest con tests.",
 perms=["elevated_admin","fs_write","net_listen"], risk="R2", isolation="Es el aislador.", approval="N/A", secrets="Contraseña DPAPI en HKLM.", injection="N/A",
 models_req=[], local_cloud="local", min_vram="0", provides=["sandbox"], consumes=[], runtime="node", transport=["in-process"], integration="drop_in",
 scores=dict(A1=4,A2=4,A3=1,A4=5,A5=5,A6=3,A7=3,A8=5,A9=4,A10=5), impact=dict(seguridad=3,claude_code=2,autonomia=1),
 claims=[("Aísla red y FS en Windows (srt-win.exe, CI windows-latest con tests)","E2"),("Filtro WFP bloquea conexiones aunque el proceso ignore el proxy","E1")],
 pros=["Anthropic; activo (60 commits/90d); tests; CI Windows","Fail-closed en red"], cons=["Windows = alpha, requiere admin en setup","No aísla el escritorio (UIA/input siguen accesibles)"],
 contradictions=[], open=["Compatibilidad con Windows 11 Home (no requiere Windows Sandbox: OK)."],
 ext=[("E1","https://github.com/anthropic-experimental/sandbox-runtime/","Windows: Alpha — uses a bundled srt-win.exe helper ... A machine-wide WFP filter set blocks all outbound connections originating from the srt-sandbox account except loopback to the proxy port range","Mecanismo Windows")],
 verdict="Sandbox de proceso con soporte Windows alpha verificado en docs y CI; no cubre el escritorio.")

add("TarunKurella/sandboxrs-windows", block="B9", archetype="windows_sandbox", name="sandboxrs-windows", stars=None,
 what="Librería Rust para lanzar procesos Windows dentro de AppContainer (sin admin) o del API experimental de sandbox de Windows, con política de FS y Job Objects; fail-closed; CI valida el claim 'no-admin' como usuario estándar.",
 problem="Aislar procesos hijos del agente sin admin, Docker, WSL ni Hyper-V.",
 how="Base para ejecutar tools/comandos del agente con autoridad de FS limitada en Windows 11 Home.",
 perception="none", actuation="none", verification="none", win="W1", win_notes="Windows 11 / Server 2025; CI windows-latest con tests como usuario estándar.",
 perms=[], risk="R0", isolation="AppContainer/Job Object.", approval="N/A", secrets="N/A", injection="N/A",
 models_req=[], local_cloud="local", min_vram="0", provides=["sandbox"], consumes=[], runtime="rust", transport=["in-process"], integration="adapter",
 scores=dict(A1=3,A2=4,A3=1,A4=5,A5=3,A6=5,A7=3,A8=4,A9=0,A10=5), impact=dict(seguridad=3,autonomia=1),
 claims=[("Sandbox sin admin","E1"),("Fail-closed","E1")], pros=["Diseño honesto (documenta límites), tests en CI como no-admin"], cons=["1 autor (bus 1.0), 22 días","AppContainer rompe herramientas de desarrollo genéricas (OpenAI documenta por qué lo descartó)"],
 contradictions=["OpenAI (Codex) descartó AppContainer por incompatibilidad con workflows de desarrollador; sandboxrs lo adopta como mecanismo principal."],
 open=["Compatibilidad con apps GUI dentro del AppContainer."],
 ext=[("E1","https://github.com/TarunKurella/sandboxrs-windows/blob/main/README.md","without asking for a daemon, a service, a kernel driver, Docker, WSL, Hyper-V, or administrator rights ... GitHub CI runs the AppContainer suite as a temporary standard user and fails if the eval reports admin: true","No-admin verificado en CI"),
      ("E3","https://openai.com/index/building-codex-windows-sandbox/","AppContainer ... Why not: Codex is not one tightly scoped app ... that made AppContainer the wrong shape for the problem ... Windows Sandbox isn't even available on Windows Home SKUs","Trade-off documentado por OpenAI")],
 verdict="HIDDEN_GEM candidato: sandbox Windows sin admin, fail-closed y probado en CI; muy joven y de un autor.")

add("ethz-spylab/agentdojo", block="B9", archetype="injection_bench", name="AgentDojo", stars=None,
 what="Benchmark dinámico de prompt injection para agentes con tools (ETH Zürich).", problem="Medir robustez del agente frente a injection.",
 how="Evaluar el agente/gateway antes de darle acceso real.", perception="none", actuation="none", verification="none", win="W1", win_notes="Python.", perms=["net_out"], risk="R0", isolation="N/A", approval="N/A", secrets="N/A", injection="Benchmark.",
 models_req=[], local_cloud="hybrid", min_vram="0", provides=["eval_harness"], consumes=["llm_client"], runtime="python", transport=["in-process"], integration="adapter",
 scores=dict(A1=4,A2=3,A3=0,A4=5,A5=2,A6=4,A7=5,A8=3,A9=3,A10=4), impact=dict(seguridad=2,precision=1),
 claims=[("Benchmark académico revisado","E3")], pros=["Académico, citado"], cons=["92 días sin commits"], contradictions=[], open=[], ext=[], verdict="Benchmark académico de injection; poco activo.")

add("TheUser99-spec/Phylax", block="B9", archetype="windows_acl", name="Phylax", stars=None,
 what="Daemon Windows (Rust) que aplica ACLs DENY + etiquetas MIC a ficheros protegidos (.env, claves) para que el kernel bloquee a procesos de agentes; dashboard y auditoría; fase 2 (minifilter) en desarrollo.",
 problem="Impedir que el agente lea secretos aunque tenga shell.", how="Complemento a un sandbox: protección de secretos a nivel NTFS.",
 perception="none", actuation="none", verification="none", win="W1", win_notes="Windows-first; CI windows-latest.", perms=["fs_write","elevated_admin"], risk="R2", isolation="ACL/MIC.", approval="Bucket [ask].", secrets="Protege.", injection="N/A",
 models_req=[], local_cloud="local", min_vram="0", provides=["sandbox"], consumes=[], runtime="rust", transport=["in-process"], integration="drop_in",
 scores=dict(A1=3,A2=2,A3=1,A4=4,A5=2,A6=4,A7=1,A8=3,A9=0,A10=5), impact=dict(seguridad=2),
 claims=[("Kernel bloquea acceso vía ACL/MIC","E1"),("Zero telemetry","E0")], pros=["Mecanismo real del SO"], cons=["2 tests, bus 0.97, 85 días","Requiere admin para MIC High; 'seeking technical review' (auto-declarado)"], contradictions=["README: 'zero telemetry'; sonda encontró 15 hits de 'telemetry' (probablemente docs/compliance): UNVERIFIED."], open=["Auditoría externa."], ext=[], verdict="Protección de secretos por ACL en Windows, inmadura (2 tests) y de un autor.")

# ---------------- B10 OBSERVABILIDAD / EVAL ----------------
add("langfuse/langfuse", block="B10", archetype="tracing", name="Langfuse", stars=34200,
 what="Plataforma open source de trazas, coste, prompts y evals para LLM apps; self-host por Docker; OTel.",
 problem="Responder '¿por qué hizo esto, qué vio, cuánto costó?'.", how="Sumidero de trazas del agente (con screenshots como adjuntos).",
 perception="none", actuation="none", verification="none", win="W4", win_notes="Self-host = Docker Compose; SDK Python/JS nativo.", perms=["net_out","fs_write","telemetry"], risk="R1", isolation="N/A", approval="N/A", secrets="Trazas pueden contener prompts/secretos.", injection="N/A",
 models_req=[], local_cloud="hybrid", min_vram="0", provides=["trace_sink"], consumes=[], runtime="ts + python sdk", transport=["http"], integration="drop_in",
 scores=dict(A1=5,A2=4,A3=1,A4=3,A5=5,A6=3,A7=2,A8=5,A9=5,A10=3), impact=dict(observabilidad=3,coste=1,tokens=1),
 claims=[("Trazas + coste + evals","E2")], pros=["14 humanos/90d, 642 tests"], cons=["Servidor requiere Docker (W4); licencia OTHER (MIT + EE)"], contradictions=[], open=[], ext=[], verdict="Observabilidad madura; servidor vía Docker en Windows.")

add("xlang-ai/OSWorld", block="B10", archetype="benchmark", name="OSWorld / OSWorld-Verified", stars=None,
 what="Benchmark de referencia de computer use (369 tareas, evaluación por ejecución) con leaderboard; OSWorld 2.0 (108 workflows largos).",
 problem="Medir agentes CU de forma reproducible.", how="Fuente de verdad para elegir modelo/harness; no se ejecuta localmente (VMs).",
 perception="none", actuation="none", verification="Evaluadores por ejecución.", win="W5", win_notes="Requiere VMs (VMware/Docker); tareas Ubuntu; variante Windows en WAA (muerto: 651 días).", perms=["exec_code"], risk="R1", isolation="VM.", approval="N/A", secrets="N/A", injection="N/A",
 models_req=[], local_cloud="local", min_vram="0", provides=["eval_harness"], consumes=[], runtime="python", transport=["in-process"], integration="adapter",
 scores=dict(A1=5,A2=3,A3=3,A4=4,A5=5,A6=1,A7=5,A8=4,A9=5,A10=2), impact=dict(precision=2,computer_use=1,observabilidad=1),
 claims=[("Leaderboard con verificación","E3")], pros=["16 humanos/90d; estándar de facto"], cons=["No ejecutable en el hardware objetivo","Leaderboards de terceros discrepan (véase contradicciones)"],
 contradictions=["Steel.dev: Mythos Preview 85.4% (mayo 2026); gentic.news: 79.6% (junio 2026); BenchLM: Qwen3.8 Max 86.1% (sept 2026) — harness/versiones distintas."], open=[],
 ext=[("E3","https://leaderboard.steel.dev/leaderboards/osworld/","Claude Mythos Preview | 85.4% ... Claude Fable 5 | 85.0% ... Claude Opus 4.8 | 83.4% ... Claude Sonnet 5 | 81.2% ... Qwen3 VL 235B | 66.7% ... Claude Haiku 4.5 | 50.7%","Leaderboard OSWorld-Verified (mayo 2026)"),
      ("E3","https://benchlm.ai/benchmarks/osworld-verified","As of September 2, 2026, Qwen3.8 Max leads the OSWorld-Verified leaderboard with 86.1%, followed by Claude Fable 5 (85%) and Claude Mythos 5 (85%) ... Qwen3.8-27B 84.3% ... Holo3-35B-A3B 82.6%","Leaderboard (sept 2026)"),
      ("E3","https://snorkel.ai/leaderboard/os-world-2-0/","At the 500-step budget, the top system completes just over 31% of tasks end-to-end. Claude Opus 5 leads at 31.43% binary completion and 68.31% partial score ... Claude Opus 4.7 | max | Standard | 13.9% | 49.1% | $3.87K","OSWorld 2.0: tareas largas siguen sin resolverse; coste por run")],
 verdict="Benchmark de referencia activo; los leaderboards de terceros no coinciden entre sí por harness/fechas.")
